<?php

namespace Database\Seeders;

use App\Models\actividades_economicas;

use Illuminate\Database\Seeder;

class ActividadesEconomicasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $actividades = [
            ['codigo'=>'01111','actividad'=>'Cultivo de cereales excepto arroz y para forrajes'],
            ['codigo'=>'01112','actividad'=>'Cultivo de legumbres'],
            ['codigo'=>'01113','actividad'=>'Cultivo de semillas oleaginosas'],
            ['codigo'=>'01114','actividad'=>'Cultivo de plantas para la preparación de semillas'],
            ['codigo'=>'01119','actividad'=>'Cultivo de otros cereales excepto arroz y forrajeros n.c.p.'],
            ['codigo'=>'01120','actividad'=>'Cultivo de arroz'],
            ['codigo'=>'01131','actividad'=>'Cultivo de raíces y tubérculos'],
            ['codigo'=>'01132','actividad'=>'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares'],
            ['codigo'=>'01133','actividad'=>'Cultivo hortícola de fruto'],
            ['codigo'=>'01134','actividad'=>'Cultivo de hortalizas de hoja y otras hortalizas ncp'],
            ['codigo'=>'01140','actividad'=>'Cultivo de caña de azúcar'],
            ['codigo'=>'01150','actividad'=>'Cultivo de tabaco'],
            ['codigo'=>'01161','actividad'=>'Cultivo de algodón'],
            ['codigo'=>'01162','actividad'=>'Cultivo de fibras vegetales excepto algodón'],
            ['codigo'=>'01191','actividad'=>'Cultivo de plantas no perennes para la producción de semillas y flores'],
            ['codigo'=>'01192','actividad'=>'Cultivo de cereales y pastos para la alimentación animal'],
            ['codigo'=>'01199','actividad'=>'Producción de cultivos no estacionales ncp'],
            ['codigo'=>'01220','actividad'=>'Cultivo de frutas tropicales'],
            ['codigo'=>'01230','actividad'=>'Cultivo de cítricos'],
            ['codigo'=>'01240','actividad'=>'Cultivo de frutas de pepita y hueso'],
            ['codigo'=>'01251','actividad'=>'Cultivo de frutas ncp'],
            ['codigo'=>'01252','actividad'=>'Cultivo de otros frutos y nueces de árboles y arbustos'],
            ['codigo'=>'01260','actividad'=>'Cultivo de frutos oleaginosos'],
            ['codigo'=>'01271','actividad'=>'Cultivo de café'],
            ['codigo'=>'01272','actividad'=>'Cultivo de plantas para la elaboración de bebidas excepto café'],
            ['codigo'=>'01281','actividad'=>'Cultivo de especias y aromáticas'],
            ['codigo'=>'01282','actividad'=>'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos'],
            ['codigo'=>'01291','actividad'=>'Cultivo de árboles de hule (caucho) para la obtención de látex'],
            ['codigo'=>'01292','actividad'=>'Cultivo de plantas para la obtención de productos químicos y colorantes'],
            ['codigo'=>'01299','actividad'=>'Producción de cultivos perennes ncp'],
            ['codigo'=>'01300','actividad'=>'Propagación de plantas'],
            ['codigo'=>'01301','actividad'=>'Cultivo de plantas y flores ornamentales'],
            ['codigo'=>'01410','actividad'=>'Cría y engorde de ganado bovino'],
            ['codigo'=>'01420','actividad'=>'Cría de caballos y otros equinos'],
            ['codigo'=>'01440','actividad'=>'Cría de ovejas y cabras'],
            ['codigo'=>'01450','actividad'=>'Cría de cerdos'],
            ['codigo'=>'01460','actividad'=>'Cría de aves de corral y producción de huevos'],
            ['codigo'=>'01491','actividad'=>'Cría de abejas apicultura para la obtención de miel y otros productos apícolas'],
            ['codigo'=>'01492','actividad'=>'Cría de conejos'],
            ['codigo'=>'01493','actividad'=>'Cría de iguanas y garrobos'],
            ['codigo'=>'01494','actividad'=>'Cría de mariposas y otros insectos'],
            ['codigo'=>'01499','actividad'=>'Cría y obtención de productos animales n.c.p.'],
            ['codigo'=>'01500','actividad'=>'Cultivo de productos agrícolas en combinación con la cría de animales'],
            ['codigo'=>'01611','actividad'=>'Servicios de maquinaria agrícola'],
            ['codigo'=>'01612','actividad'=>'Control de plagas'],
            ['codigo'=>'01613','actividad'=>'Servicios de riego'],
            ['codigo'=>'01614','actividad'=>'Servicios de contratación de mano de obra para la agricultura'],
            ['codigo'=>'01619','actividad'=>'Servicios agrícolas ncp'],
            ['codigo'=>'01621','actividad'=>'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos'],
            ['codigo'=>'01622','actividad'=>'Servicios de mano de obra pecuaria'],
            ['codigo'=>'01629','actividad'=>'Servicios pecuarios ncp'],
            ['codigo'=>'01631','actividad'=>'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria'],
            ['codigo'=>'01632','actividad'=>'Servicio de beneficio de café'],
            ['codigo'=>'01633','actividad'=>'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria)'],
            ['codigo'=>'01640','actividad'=>'Tratamiento de semillas para la propagación'],
            ['codigo'=>'01700','actividad'=>'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos'],
            ['codigo'=>'02100','actividad'=>'Silvicultura y otras actividades forestales'],
            ['codigo'=>'02200','actividad'=>'Extracción de madera'],
            ['codigo'=>'02300','actividad'=>'Recolección de productos diferentes a la madera'],
            ['codigo'=>'02400','actividad'=>'Servicios de apoyo a la silvicultura'],
            ['codigo'=>'03110','actividad'=>'Pesca marítima de altura y costera'],
            ['codigo'=>'03120','actividad'=>'Pesca de agua dulce'],
            ['codigo'=>'03210','actividad'=>'Acuicultura marítima'],
            ['codigo'=>'03220','actividad'=>'Acuicultura de agua dulce'],
            ['codigo'=>'03300','actividad'=>'Servicios de apoyo a la pesca y acuicultura'],
            ['codigo'=>'05100','actividad'=>'Extracción de hulla'],
            ['codigo'=>'05200','actividad'=>'Extracción y aglomeración de lignito'],
            ['codigo'=>'06100','actividad'=>'Extracción de petróleo crudo'],
            ['codigo'=>'06200','actividad'=>'Extracción de gas natural'],
            ['codigo'=>'07100','actividad'=>'Extracción de minerales de hierro'],
            ['codigo'=>'07210','actividad'=>'Extracción de minerales de uranio y torio'],
            ['codigo'=>'07290','actividad'=>'Extracción de minerales metalíferos no ferrosos'],
            ['codigo'=>'08100','actividad'=>'Extracción de piedra, arena y arcilla'],
            ['codigo'=>'08910','actividad'=>'Extracción de minerales para la fabricación de abonos y productos químicos'],
            ['codigo'=>'08920','actividad'=>'Extracción y aglomeración de turba'],
            ['codigo'=>'08930','actividad'=>'Extracción de sal'],
            ['codigo'=>'08990','actividad'=>'Explotación de otras minas y canteras ncp'],
            ['codigo'=>'09100','actividad'=>'Actividades de apoyo a la extracción de petróleo y gas natural'],
            ['codigo'=>'09900','actividad'=>'Actividades de apoyo a la explotación de minas y canteras'],
            ['codigo'=>'10101','actividad'=>'Servicio de rastros y mataderos de bovinos y porcinos'],
            ['codigo'=>'10102','actividad'=>'Matanza y procesamiento de bovinos y porcinos'],
            ['codigo'=>'10103','actividad'=>'Matanza y procesamientos de aves de corral'],
            ['codigo'=>'10104','actividad'=>'Elaboración y conservación de embutidos y tripas naturales'],
            ['codigo'=>'10105','actividad'=>'Servicios de conservación y empaque de carnes'],
            ['codigo'=>'10106','actividad'=>'Elaboración y conservación de grasas y aceites animales'],
            ['codigo'=>'10107','actividad'=>'Servicios de molienda de carne'],
            ['codigo'=>'10108','actividad'=>'Elaboración de productos de carne ncp'],
            ['codigo'=>'10201','actividad'=>'Procesamiento y conservación de pescado, crustáceos y moluscos'],
            ['codigo'=>'10209','actividad'=>'Fabricación de productos de pescado ncp'],
            ['codigo'=>'10301','actividad'=>'Elaboración de jugos de frutas y hortalizas'],
            ['codigo'=>'10302','actividad'=>'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas'],
            ['codigo'=>'10309','actividad'=>'Elaboración de productos de frutas y hortalizas n.c.p.'],
            ['codigo'=>'10401','actividad'=>'Fabricación de aceites y grasas vegetales y animales comestibles'],
            ['codigo'=>'10402','actividad'=>'Fabricación de aceites y grasas vegetales y animales no comestibles'],
            ['codigo'=>'10409','actividad'=>'Servicio de maquilado de aceites'],
            ['codigo'=>'10501','actividad'=>'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos'],
            ['codigo'=>'10502','actividad'=>'Fabricación de sorbetes y helados'],
            ['codigo'=>'10503','actividad'=>'Fabricación de quesos'],
            ['codigo'=>'10611','actividad'=>'Molienda de cereales'],
            ['codigo'=>'10612','actividad'=>'Elaboración de cereales para el desayuno y similares'],
            ['codigo'=>'10613','actividad'=>'Servicios de beneficiado de productos agrícolas ncp (excluye beneficio de azúcar rama 1072 y beneficio de café rama 0163)'],
            ['codigo'=>'10621','actividad'=>'Fabricación de almidón'],
            ['codigo'=>'10628','actividad'=>'Servicio de molienda de maíz húmedo molino para nixtamal'],
            ['codigo'=>'10711','actividad'=>'Elaboración de tortillas'],
            ['codigo'=>'10712','actividad'=>'Fabricación de pan, galletas y barquillos'],
            ['codigo'=>'10713','actividad'=>'Fabricación de repostería'],
            ['codigo'=>'10721','actividad'=>'Ingenios azucareros'],
            ['codigo'=>'10722','actividad'=>'Molienda de caña de azúcar para la elaboración de dulces'],
            ['codigo'=>'10723','actividad'=>'Elaboración de jarabes de azúcar y otros similares'],
            ['codigo'=>'10724','actividad'=>'Maquilado de azúcar de caña'],
            ['codigo'=>'10730','actividad'=>'Fabricación de cacao, chocolates y productos de confitería'],
            ['codigo'=>'10740','actividad'=>'Elaboración de macarrones, fideos, y productos farináceos similares'],
            ['codigo'=>'10750','actividad'=>'Elaboración de comidas y platos preparados para la reventa en locales y/o para exportación'],
            ['codigo'=>'10791','actividad'=>'Elaboración de productos de café'],
            ['codigo'=>'10792','actividad'=>'Elaboración de especies, sazonadores y condimentos'],
            ['codigo'=>'10793','actividad'=>'Elaboración de sopas, cremas y consomé'],
            ['codigo'=>'10794','actividad'=>'Fabricación de bocadillos tostados y/o fritos'],
            ['codigo'=>'10799','actividad'=>'Elaboración de productos alimenticios ncp'],
            ['codigo'=>'10800','actividad'=>'Elaboración de alimentos preparados para animales'],
            ['codigo'=>'11012','actividad'=>'Fabricación de aguardiente y licores'],
            ['codigo'=>'11020','actividad'=>'Elaboración de vinos'],
            ['codigo'=>'11030','actividad'=>'Fabricación de cerveza'],
            ['codigo'=>'11041','actividad'=>'Fabricación de aguas gaseosas'],
            ['codigo'=>'11042','actividad'=>'Fabricación y envasado de agua'],
            ['codigo'=>'11043','actividad'=>'Elaboración de refrescos'],
            ['codigo'=>'11048','actividad'=>'Maquilado de aguas gaseosas'],
            ['codigo'=>'11049','actividad'=>'Elaboración de bebidas no alcohólicas'],
            ['codigo'=>'12000','actividad'=>'Elaboración de productos de tabaco'],
            ['codigo'=>'13111','actividad'=>'Preparación de fibras textiles'],
            ['codigo'=>'13112','actividad'=>'Fabricación de hilados'],
            ['codigo'=>'13120','actividad'=>'Fabricación de telas'],
            ['codigo'=>'13130','actividad'=>'Acabado de productos textiles'],
            ['codigo'=>'13910','actividad'=>'Fabricación de tejidos de punto y ganchillo'],
            ['codigo'=>'13921','actividad'=>'Fabricación de productos textiles para el hogar'],
            ['codigo'=>'13922','actividad'=>'Sacos, bolsas y otros artículos textiles'],
            ['codigo'=>'13929','actividad'=>'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir n.c.p'],
            ['codigo'=>'13930','actividad'=>'Fabricación de tapices y alfombras'],
            ['codigo'=>'13941','actividad'=>'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas)'],
            ['codigo'=>'13942','actividad'=>'Fabricación de redes de diversos materiales'],
            ['codigo'=>'13948','actividad'=>'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.)'],
            ['codigo'=>'13991','actividad'=>'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir'],
            ['codigo'=>'13992','actividad'=>'Servicio de bordados en artículos y prendas de tela'],
            ['codigo'=>'13999','actividad'=>'Fabricación de productos textiles ncp'],
            ['codigo'=>'14101','actividad'=>'Fabricación de ropa interior, para dormir y similares'],
            ['codigo'=>'14102','actividad'=>'Fabricación de ropa para niños'],
            ['codigo'=>'14103','actividad'=>'Fabricación de prendas de vestir para ambos sexos'],
            ['codigo'=>'14104','actividad'=>'Confección de prendas a medida'],
            ['codigo'=>'14105','actividad'=>'Fabricación de prendas de vestir para deportes'],
            ['codigo'=>'14106','actividad'=>'Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles'],
            ['codigo'=>'14108','actividad'=>'Maquilado de prendas de vestir, accesorios y otros'],
            ['codigo'=>'14109','actividad'=>'Fabricación de prendas y accesorios de vestir n.c.p.'],
            ['codigo'=>'14200','actividad'=>'Fabricación de artículos de piel'],
            ['codigo'=>'14301','actividad'=>'Fabricación de calcetines, calcetas, medias (panty house) y otros similares'],
            ['codigo'=>'14302','actividad'=>'Fabricación de ropa interior de tejido de punto'],
            ['codigo'=>'14309','actividad'=>'Fabricación de prendas de vestir de tejido de punto ncp'],
            ['codigo'=>'15110','actividad'=>'Curtido y adobo de cueros; adobo y teñido de pieles'],
            ['codigo'=>'15121','actividad'=>'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería'],
            ['codigo'=>'15122','actividad'=>'Fabricación de monturas, accesorios y vainas talabartería'],
            ['codigo'=>'15123','actividad'=>'Fabricación de artesanías principalmente de cuero natural y sintético'],
            ['codigo'=>'15128','actividad'=>'Maquilado de artículos de cuero natural, sintético y de otros materiales'],
            ['codigo'=>'15201','actividad'=>'Fabricación de calzado'],
            ['codigo'=>'15202','actividad'=>'Fabricación de partes y accesorios de calzado'],
            ['codigo'=>'15208','actividad'=>'Maquilado de partes y accesorios de calzado'],
            ['codigo'=>'16100','actividad'=>'Aserradero y acepilladura de madera'],
            ['codigo'=>'16210','actividad'=>'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción'],
            ['codigo'=>'16220','actividad'=>'Fabricación de partes y piezas de carpintería para edificios y construcciones'],
            ['codigo'=>'16230','actividad'=>'Fabricación de envases y recipientes de madera'],
            ['codigo'=>'16292','actividad'=>'Fabricación de artesanías de madera, semillas, materiales trenzables'],
            ['codigo'=>'16299','actividad'=>'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp'],
            ['codigo'=>'17010','actividad'=>'Fabricación de pasta de madera, papel y cartón'],
            ['codigo'=>'17020','actividad'=>'Fabricación de papel y cartón ondulado y envases de papel y cartón'],
            ['codigo'=>'17091','actividad'=>'Fabricación de artículos de papel y cartón de uso personal y doméstico'],
            ['codigo'=>'17092','actividad'=>'Fabricación de productos de papel ncp'],
            ['codigo'=>'18110','actividad'=>'Impresión'],
            ['codigo'=>'18120','actividad'=>'Servicios relacionados con la impresión'],
            ['codigo'=>'18200','actividad'=>'Reproducción de grabaciones'],
            ['codigo'=>'19100','actividad'=>'Fabricación de productos de hornos de coque'],
            ['codigo'=>'19201','actividad'=>'Fabricación de combustible'],
            ['codigo'=>'19202','actividad'=>'Fabricación de aceites y lubricantes'],
            ['codigo'=>'20111','actividad'=>'Fabricación de materias primas para la fabricación de colorantes'],
            ['codigo'=>'20112','actividad'=>'Fabricación de materiales curtientes'],
            ['codigo'=>'20113','actividad'=>'Fabricación de gases industriales'],
            ['codigo'=>'20114','actividad'=>'Fabricación de alcohol etílico'],
            ['codigo'=>'20119','actividad'=>'Fabricación de sustancias químicas básicas'],
            ['codigo'=>'20120','actividad'=>'Fabricación de abonos y fertilizantes'],
            ['codigo'=>'20130','actividad'=>'Fabricación de plástico y caucho en formas primarias'],
            ['codigo'=>'20210','actividad'=>'Fabricación de plaguicidas y otros productos químicos de uso agropecuario'],
            ['codigo'=>'20220','actividad'=>'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas'],
            ['codigo'=>'20231','actividad'=>'Fabricación de jabones, detergentes y similares para limpieza'],
            ['codigo'=>'20232','actividad'=>'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc.'],
            ['codigo'=>'20291','actividad'=>'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras'],
            ['codigo'=>'20292','actividad'=>'Fabricación de productos pirotécnicos, explosivos y municiones'],
            ['codigo'=>'20299','actividad'=>'Fabricación de productos químicos n.c.p.'],
            ['codigo'=>'20300','actividad'=>'Fabricación de fibras artificiales'],
            ['codigo'=>'21001','actividad'=>'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos'],
            ['codigo'=>'21008','actividad'=>'Maquilado de medicamentos'],
            ['codigo'=>'22110','actividad'=>'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas'],
            ['codigo'=>'22190','actividad'=>'Fabricación de otros productos de caucho'],
            ['codigo'=>'22201','actividad'=>'Fabricación de envases plásticos'],
            ['codigo'=>'22202','actividad'=>'Fabricación de productos plásticos para uso personal o doméstico'],
            ['codigo'=>'22208','actividad'=>'Maquila de plásticos'],
            ['codigo'=>'22209','actividad'=>'Fabricación de productos plásticos n.c.p.'],
            ['codigo'=>'23101','actividad'=>'Fabricación de vidrio'],
            ['codigo'=>'23102','actividad'=>'Fabricación de recipientes y envases de vidrio especial'],
            ['codigo'=>'23108','actividad'=>'Servicio de maquilado'],
            ['codigo'=>'23109','actividad'=>'Fabricación de productos de vidrio ncp'],
            ['codigo'=>'23910','actividad'=>'Fabricación de productos refractarios'],
            ['codigo'=>'23920','actividad'=>'Fabricación de productos de arcilla para la construcción'],
            ['codigo'=>'23931','actividad'=>'Fabricación de productos de cerámica y porcelana no refractaria'],
            ['codigo'=>'23932','actividad'=>'Fabricación de productos de cerámica y porcelana ncp'],
            ['codigo'=>'23940','actividad'=>'Fabricación de cemento, cal y yeso'],
            ['codigo'=>'23950','actividad'=>'Fabricación de articulos de hormigón, cemento y yeso'],
            ['codigo'=>'23960','actividad'=>'Corte, tallado y acabado de la piedra'],
            ['codigo'=>'23990','actividad'=>'Fabricación de productos minerales no metálicos ncp'],
            ['codigo'=>'24100','actividad'=>'Industrias básicas de hierro y acero'],
            ['codigo'=>'24200','actividad'=>'Fabricación de productos primarios de metales preciosos y metales no ferrosos'],
            ['codigo'=>'24310','actividad'=>'Fundición de hierro y acero'],
            ['codigo'=>'24320','actividad'=>'Fundición de metales no ferrosos'],
            ['codigo'=>'25111','actividad'=>'Fabricación de productos metálicos para uso estructural'],
            ['codigo'=>'25118','actividad'=>'Servicio de maquila para la fabricación de estructuras metálicas'],
            ['codigo'=>'25120','actividad'=>'Fabricación de tanques, depósitos y recipientes de metal'],
            ['codigo'=>'25130','actividad'=>'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central'],
            ['codigo'=>'25200','actividad'=>'Fabricación de armas y municiones'],
            ['codigo'=>'25910','actividad'=>'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia'],
            ['codigo'=>'25920','actividad'=>'Tratamiento y revestimiento de metales'],
            ['codigo'=>'25930','actividad'=>'Fabricación de artículos de cuchilleria, herramientas de mano y artículos de ferreteria'],
            ['codigo'=>'25991','actividad'=>'Fabricación de envases y artículos conexos de metal'],
            ['codigo'=>'25992','actividad'=>'Fabricación de artículos metálicos de uso personal y/o doméstico'],
            ['codigo'=>'25999','actividad'=>'Fabricación de productos elaborados de metal ncp'],
            ['codigo'=>'26100','actividad'=>'Fabricación de componentes electrónicos'],
            ['codigo'=>'26200','actividad'=>'Fabricación de computadoras y equipo conexo'],
            ['codigo'=>'26300','actividad'=>'Fabricación de equipo de comunicaciones'],
            ['codigo'=>'26400','actividad'=>'Fabricación de aparatos electrónicos de consumo para audio, video, radio y televisión'],
            ['codigo'=>'26510','actividad'=>'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales'],
            ['codigo'=>'26520','actividad'=>'Fabricación de relojes y piezas de relojes'],
            ['codigo'=>'26600','actividad'=>'Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico'],
            ['codigo'=>'26700','actividad'=>'Fabricación de instrumentos de óptica y equipo fotográfico'],
            ['codigo'=>'26800','actividad'=>'Fabricación de medios magnéticos y ópticos'],
            ['codigo'=>'27100','actividad'=>'Fabricación de motores, generadores, transformadores eléctricos, aparatos de distribución y control de electricidad'],
            ['codigo'=>'27200','actividad'=>'Fabricación de pilas, baterías y acumuladores'],
            ['codigo'=>'27310','actividad'=>'Fabricación de cables de fibra óptica'],
            ['codigo'=>'27320','actividad'=>'Fabricación de otros hilos y cables eléctricos'],
            ['codigo'=>'27330','actividad'=>'Fabricación de dispositivos de cableados'],
            ['codigo'=>'27400','actividad'=>'Fabricación de equipo eléctrico de iluminación'],
            ['codigo'=>'27500','actividad'=>'Fabricación de aparatos de uso doméstico'],
            ['codigo'=>'27900','actividad'=>'Fabricación de otros tipos de equipo eléctrico'],
            ['codigo'=>'28110','actividad'=>'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas'],
            ['codigo'=>'28120','actividad'=>'Fabricación de equipo hidráulico'],
            ['codigo'=>'28130','actividad'=>'Fabricación de otras bombas, compresores, grifos y válvulas'],
            ['codigo'=>'28140','actividad'=>'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión'],
            ['codigo'=>'28150','actividad'=>'Fabricación de hornos y quemadores'],
            ['codigo'=>'28160','actividad'=>'Fabricación de equipo de elevación y manipulación'],
            ['codigo'=>'28170','actividad'=>'Fabricación de maquinaria y equipo de oficina'],
            ['codigo'=>'28180','actividad'=>'Fabricación de herramientas manuales'],
            ['codigo'=>'28190','actividad'=>'Fabricación de otros tipos de maquinaria de uso general'],
            ['codigo'=>'28210','actividad'=>'Fabricación de maquinaria agropecuaria y forestal'],
            ['codigo'=>'28220','actividad'=>'Fabricación de máquinas para conformar metales y maquinaria herramienta'],
            ['codigo'=>'28230','actividad'=>'Fabricación de maquinaria metalúrgica'],
            ['codigo'=>'28240','actividad'=>'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción'],
            ['codigo'=>'28250','actividad'=>'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco'],
            ['codigo'=>'28260','actividad'=>'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros'],
            ['codigo'=>'28291','actividad'=>'Fabricación de máquinas para imprenta'],
            ['codigo'=>'28299','actividad'=>'Fabricación de maquinaria de uso especial ncp'],
            ['codigo'=>'29100','actividad'=>'Fabricación vehículos automotores'],
            ['codigo'=>'29200','actividad'=>'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semiremolques'],
            ['codigo'=>'29300','actividad'=>'Fabricación de partes, piezas y accesorios para vehículos automotores'],
            ['codigo'=>'30110','actividad'=>'Fabricación de buques'],
            ['codigo'=>'30120','actividad'=>'Construcción y reparación de embarcaciones de recreo'],
            ['codigo'=>'30200','actividad'=>'Fabricación de locomotoras y de material rodante'],
            ['codigo'=>'30300','actividad'=>'Fabricación de aeronaves y naves espaciales'],
            ['codigo'=>'30400','actividad'=>'Fabricación de vehículos militares de combate'],
            ['codigo'=>'30910','actividad'=>'Fabricación de motocicletas'],
            ['codigo'=>'30920','actividad'=>'Fabricación de bicicletas y sillones de ruedas para inválidos'],
            ['codigo'=>'30990','actividad'=>'Fabricación de equipo de transporte ncp'],
            ['codigo'=>'31001','actividad'=>'Fabricación de colchones y somier'],
            ['codigo'=>'31002','actividad'=>'Fabricación de muebles y otros productos de madera a medida'],
            ['codigo'=>'31008','actividad'=>'Servicios de maquilado de muebles'],
            ['codigo'=>'31009','actividad'=>'Fabricación de muebles ncp'],
            ['codigo'=>'32110','actividad'=>'Fabricación de joyas platerías y joyerías'],
            ['codigo'=>'32120','actividad'=>'Fabricación de joyas de imitación (fantasía) y artículos conexos'],
            ['codigo'=>'32200','actividad'=>'Fabricación de instrumentos musicales'],
            ['codigo'=>'32301','actividad'=>'Fabricación de artículos de deporte'],
            ['codigo'=>'32308','actividad'=>'Servicio de maquila de productos deportivos'],
            ['codigo'=>'32401','actividad'=>'Fabricación de juegos de mesa y de salón'],
            ['codigo'=>'32402','actividad'=>'Servicio de maquilado de juguetes y juegos'],
            ['codigo'=>'32409','actividad'=>'Fabricación de juegos y juguetes n.c.p.'],
            ['codigo'=>'32500','actividad'=>'Fabricación de instrumentos y materiales médicos y odontológicos'],
            ['codigo'=>'32901','actividad'=>'Fabricación de lápices, bolígrafos, sellos y artículos de librería en general'],
            ['codigo'=>'32902','actividad'=>'Fabricación de escobas, cepillos, pinceles y similares'],
            ['codigo'=>'32903','actividad'=>'Fabricación de artesanías de materiales diversos'],
            ['codigo'=>'32904','actividad'=>'Fabricación de artículos de uso personal y domésticos n.c.p'],
            ['codigo'=>'32905','actividad'=>'Fabricación de accesorios para las confecciones y la marroquinería n.c.p'],
            ['codigo'=>'32908','actividad'=>'Servicios de maquila ncp'],
            ['codigo'=>'32909','actividad'=>'Fabricación de productos manufacturados n.c.p.'],
            ['codigo'=>'33110','actividad'=>'Reparación y mantenimiento de productos elaborados de metal'],
            ['codigo'=>'33120','actividad'=>'Reparación y mantenimiento de maquinaria'],
            ['codigo'=>'33130','actividad'=>'Reparación y mantenimiento de equipo electrónico y óptico'],
            ['codigo'=>'33140','actividad'=>'Reparación y mantenimiento de equipo eléctrico'],
            ['codigo'=>'33150','actividad'=>'Reparación y mantenimiento de equipo de transporte, excepto vehículos automotores'],
            ['codigo'=>'33190','actividad'=>'Reparación y mantenimiento de equipos n.c.p.'],
            ['codigo'=>'33200','actividad'=>'Instalación de maquinaria y equipo industrial'],
            ['codigo'=>'35101','actividad'=>'Generación de energía eléctrica'],
            ['codigo'=>'35102','actividad'=>'Transmisión de energía eléctrica'],
            ['codigo'=>'35103','actividad'=>'Distribución de energía eléctrica'],
            ['codigo'=>'35200','actividad'=>'Fabricación de gas, distribución de combustibles gaseosos por tuberías'],
            ['codigo'=>'35300','actividad'=>'Suministro de vapor y agua caliente'],
            ['codigo'=>'36000','actividad'=>'Captación, tratamiento y suministro de agua'],
            ['codigo'=>'37000','actividad'=>'Evacuación de aguas residuales (alcantarillado)'],
            ['codigo'=>'38110','actividad'=>'Recolección y transporte de desechos sólidos provenientes de hogares y sector urbano'],
            ['codigo'=>'38120','actividad'=>'Recolección de desechos peligrosos'],
            ['codigo'=>'38210','actividad'=>'Tratamiento y eliminación de desechos inicuos'],
            ['codigo'=>'38220','actividad'=>'Tratamiento y eliminación de desechos peligrosos'],
            ['codigo'=>'38301','actividad'=>'Reciclaje de desperdicios y desechos textiles'],
            ['codigo'=>'38302','actividad'=>'Reciclaje de desperdicios y desechos de plástico y caucho'],
            ['codigo'=>'38303','actividad'=>'Reciclaje de desperdicios y desechos de vidrio'],
            ['codigo'=>'38304','actividad'=>'Reciclaje de desperdicios y desechos de papel y cartón'],
            ['codigo'=>'38305','actividad'=>'Reciclaje de desperdicios y desechos metálicos'],
            ['codigo'=>'38309','actividad'=>'Reciclaje de desperdicios y desechos no metálicos n.c.p.'],
            ['codigo'=>'39000','actividad'=>'Actividades de Saneamiento y otros Servicios de Gestión de Desechos'],
            ['codigo'=>'41001','actividad'=>'Construcción de edificios residenciales'],
            ['codigo'=>'41002','actividad'=>'Construcción de edificios no residenciales'],
            ['codigo'=>'42100','actividad'=>'Construcción de carreteras, calles y caminos'],
            ['codigo'=>'42200','actividad'=>'Construcción de proyectos de servicio público'],
            ['codigo'=>'42900','actividad'=>'Construcción de obras de ingeniería civil n.c.p'],
            ['codigo'=>'43110','actividad'=>'Demolición'],
            ['codigo'=>'43120','actividad'=>'Preparación de terreno'],
            ['codigo'=>'43210','actividad'=>'Instalaciones eléctricas'],
            ['codigo'=>'43220','actividad'=>'Instalación de fontanería, calefacción y aire acondicionado'],
            ['codigo'=>'43290','actividad'=>'Otras instalaciones para obras de construcción'],
            ['codigo'=>'43300','actividad'=>'Terminación y acabado de edificios'],
            ['codigo'=>'43900','actividad'=>'Otras actividades especializadas de construcción'],
            ['codigo'=>'43901','actividad'=>'Fabricación de techos y materiales diversos'],
            ['codigo'=>'45100','actividad'=>'Venta de vehículos automotores'],
            ['codigo'=>'45201','actividad'=>'Reparación mecánica de vehículos automotores'],
            ['codigo'=>'45202','actividad'=>'Reparaciones eléctricas del automotor y recarga de baterías'],
            ['codigo'=>'45203','actividad'=>'Enderezado y pintura de vehículos automotores'],
            ['codigo'=>'45204','actividad'=>'Reparaciones de radiadores, escapes y silenciadores'],
            ['codigo'=>'45205','actividad'=>'Reparación y reconstrucción de vías, stop y otros artículos de fibra de vidrio'],
            ['codigo'=>'45206','actividad'=>'Reparación de llantas de vehículos automotores'],
            ['codigo'=>'45207','actividad'=>'Polarizado de vehículos (mediante la adhesión de papel especial a los vidrios)'],
            ['codigo'=>'45208','actividad'=>'Lavado y pasteado de vehículos (carwash)'],
            ['codigo'=>'45209','actividad'=>'Reparaciones de vehículos n.c.p'],
            ['codigo'=>'45211','actividad'=>'Remolque de vehículos automotores'],
            ['codigo'=>'45301','actividad'=>'Venta de partes, piezas y accesorios nuevos para vehículos automotores'],
            ['codigo'=>'45302','actividad'=>'Venta de partes, piezas y accesorios usados para vehículos automotores'],
            ['codigo'=>'45401','actividad'=>'Venta de motocicletas'],
            ['codigo'=>'45402','actividad'=>'Venta de repuestos, piezas y accesorios de motocicletas'],
            ['codigo'=>'45403','actividad'=>'Mantenimiento y reparación de motocicletas'],
            ['codigo'=>'46100','actividad'=>'Venta al por mayor a cambio de retribución o por contratación'],
            ['codigo'=>'46201','actividad'=>'Venta al por mayor de materias primas agrícolas'],
            ['codigo'=>'46202','actividad'=>'Venta al por mayor de productos de la silvicultura'],
            ['codigo'=>'46203','actividad'=>'Venta al por mayor de productos pecuarios y de granja'],
            ['codigo'=>'46211','actividad'=>'Venta de productos para uso agropecuario'],
            ['codigo'=>'46291','actividad'=>'Venta al por mayor de granos básicos (cereales, leguminosas)'],
            ['codigo'=>'46292','actividad'=>'Venta al por mayor de semillas mejoradas para cultivo'],
            ['codigo'=>'46293','actividad'=>'Venta al por mayor de café oro y uva'],
            ['codigo'=>'46294','actividad'=>'Venta al por mayor de caña de azúcar'],
            ['codigo'=>'46295','actividad'=>'Venta al por mayor de flores, plantas y otros productos naturales'],
            ['codigo'=>'46296','actividad'=>'Venta al por mayor de productos agrícolas'],
            ['codigo'=>'46297','actividad'=>'Venta al por mayor de ganado bovino (vivo)'],
            ['codigo'=>'46298','actividad'=>'Venta al por mayor de animales porcinos, ovinos, caprino, canículas, apícolas, avícolas vivos'],
            ['codigo'=>'46299','actividad'=>'Venta de otras especies vivas del reino animal'],
            ['codigo'=>'46301','actividad'=>'Venta al por mayor de alimentos'],
            ['codigo'=>'46302','actividad'=>'Venta al por mayor de bebidas'],
            ['codigo'=>'46303','actividad'=>'Venta al por mayor de tabaco'],
            ['codigo'=>'46371','actividad'=>'Venta al por mayor de frutas, hortalizas (verduras), legumbres y tubérculos'],
            ['codigo'=>'46372','actividad'=>'Venta al por mayor de pollos, gallinas destazadas, pavos y otras aves'],
            ['codigo'=>'46373','actividad'=>'Venta al por mayor de carne bovina y porcina, productos de carne y embutidos'],
            ['codigo'=>'46374','actividad'=>'Venta al por mayor de huevos'],
            ['codigo'=>'46375','actividad'=>'Venta al por mayor de productos lácteos'],
            ['codigo'=>'46376','actividad'=>'Venta al por mayor de productos farináceos de panadería (pan dulce, cakes, repostería, etc)'],
            ['codigo'=>'46377','actividad'=>'Venta al por mayor de pastas alimenticias, aceites y grasas comestibles vegetal y animal'],
            ['codigo'=>'46378','actividad'=>'Venta al por mayor de sal comestible'],
            ['codigo'=>'46379','actividad'=>'Venta al por mayor de azúcar'],
            ['codigo'=>'46391','actividad'=>'Venta al por mayor de abarrotes (vinos, licores, productos alimenticios envasados, etc)'],
            ['codigo'=>'46392','actividad'=>'Venta al por mayor de aguas gaseosas'],
            ['codigo'=>'46393','actividad'=>'Venta al por mayor de agua purificada'],
            ['codigo'=>'46394','actividad'=>'Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo'],
            ['codigo'=>'46395','actividad'=>'Venta al por mayor de cerveza y licores'],
            ['codigo'=>'46396','actividad'=>'Venta al por mayor de hielo'],
            ['codigo'=>'46411','actividad'=>'Venta al por mayor de hilados, tejidos y productos textiles de mercería'],
            ['codigo'=>'46412','actividad'=>'Venta al por mayor de artículos textiles excepto confecciones para el hogar'],
            ['codigo'=>'46413','actividad'=>'Venta al por mayor de confecciones textiles para el hogar'],
            ['codigo'=>'46414','actividad'=>'Venta al por mayor de prendas de vestir y accesorios de vestir'],
            ['codigo'=>'46415','actividad'=>'Venta al por mayor de ropa usada'],
            ['codigo'=>'46416','actividad'=>'Venta al por mayor de calzado'],
            ['codigo'=>'46417','actividad'=>'Venta al por mayor de artículos de marroquinería y talabartería'],
            ['codigo'=>'46418','actividad'=>'Venta al por mayor de artículos de peletería'],
            ['codigo'=>'46419','actividad'=>'Venta al por mayor de otros artículos textiles n.c.p.'],
            ['codigo'=>'46471','actividad'=>'Venta al por mayor de instrumentos musicales'],
            ['codigo'=>'46472','actividad'=>'Venta al por mayor de colchones, almohadas, cojines, etc'],
            ['codigo'=>'46473','actividad'=>'Venta al por mayor de artículos de aluminio para el hogar y para otros usos'],
            ['codigo'=>'46474','actividad'=>'Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax y no desechables'],
            ['codigo'=>'46475','actividad'=>'Venta al por mayor de cámaras fotográficas, accesorios y materiales'],
            ['codigo'=>'46482','actividad'=>'Venta al por mayor de medicamentos, artículos y otros productos de uso veterinario'],
            ['codigo'=>'46483','actividad'=>'Venta al por mayor de productos y artículos de belleza y de uso personal'],
            ['codigo'=>'46484','actividad'=>'Venta de productos farmacéuticos y medicinales'],
            ['codigo'=>'46491','actividad'=>'Venta al por mayor de productos medicinales, cosméticos, perfumería y productos de limpieza'],
            ['codigo'=>'46492','actividad'=>'Venta al por mayor de relojes y artículos de joyería'],
            ['codigo'=>'46493','actividad'=>'Venta al por mayor de electrodomésticos y artículos del hogar excepto bazar; artículos de iluminación'],
            ['codigo'=>'46494','actividad'=>'Venta al por mayor de artículos de bazar y similares'],
            ['codigo'=>'46495','actividad'=>'Venta al por mayor de artículos de óptica'],
            ['codigo'=>'46496','actividad'=>'Venta al por mayor de revistas, periódicos, libros, artículos de librería y artículos de papel y cartón en general'],
            ['codigo'=>'46497','actividad'=>'Venta de artículos deportivos, juguetes y rodados'],
            ['codigo'=>'46498','actividad'=>'Venta al por mayor de productos usados para el hogar o el uso personal'],
            ['codigo'=>'46499','actividad'=>'Venta al por mayor de enseres domésticos y de uso personal n.c.p.'],
            ['codigo'=>'46500','actividad'=>'Venta al por mayor de bicicletas, partes, accesorios y otros'],
            ['codigo'=>'46510','actividad'=>'Venta al por mayor de computadoras, equipo periférico y programas informáticos'],
            ['codigo'=>'46520','actividad'=>'Venta al por mayor de equipos de comunicación'],
            ['codigo'=>'46530','actividad'=>'Venta al por mayor de maquinaria y equipo agropecuario, accesorios, partes y suministros'],
            ['codigo'=>'46590','actividad'=>'Venta de equipos e instrumentos de uso profesional y científico y aparatos de medida y control'],
            ['codigo'=>'46591','actividad'=>'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria de la madera y sus productos'],
            ['codigo'=>'46592','actividad'=>'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria gráfica y del papel, cartón y productos de papel y cartón'],
            ['codigo'=>'46593','actividad'=>'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria de productos químicos, plástico y caucho'],
            ['codigo'=>'46594','actividad'=>'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria metálica y de sus productos'],
            ['codigo'=>'46595','actividad'=>'Venta al por mayor de equipamiento para uso médico, odontológico, veterinario y servicios conexos'],
            ['codigo'=>'46596','actividad'=>'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria de la alimentación'],
            ['codigo'=>'46597','actividad'=>'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria textil, confecciones y cuero'],
            ['codigo'=>'46598','actividad'=>'Venta al por mayor de maquinaria, equipo y accesorios para la construcción y explotación de minas y canteras'],
            ['codigo'=>'46599','actividad'=>'Venta al por mayor de otro tipo de maquinaria y equipo con sus accesorios y partes'],
            ['codigo'=>'46610','actividad'=>'Venta al por mayor de otros combustibles sólidos, líquidos, gaseosos y de productos conexos'],
            ['codigo'=>'46612','actividad'=>'Venta al por mayor de combustibles para automotores, aviones, barcos, maquinaria y otros'],
            ['codigo'=>'46613','actividad'=>'Venta al por mayor de lubricantes, grasas y otros aceites para automotores, maquinaria industrial, etc.'],
            ['codigo'=>'46614','actividad'=>'Venta al por mayor de gas propano'],
            ['codigo'=>'46615','actividad'=>'Venta al por mayor de leña y carbón'],
            ['codigo'=>'46620','actividad'=>'Venta al por mayor de metales y minerales metalíferos'],
            ['codigo'=>'46631','actividad'=>'Venta al por mayor de puertas, ventanas, vitrinas y similares'],
            ['codigo'=>'46632','actividad'=>'Venta al por mayor de artículos de ferretería y pinturerías'],
            ['codigo'=>'46633','actividad'=>'Vidrierías'],
            ['codigo'=>'46634','actividad'=>'Venta al por mayor de maderas'],
            ['codigo'=>'46639','actividad'=>'Venta al por mayor de materiales para la construcción n.c.p.'],
            ['codigo'=>'46691','actividad'=>'Venta al por mayor de sal industrial sin yodar'],
            ['codigo'=>'46692','actividad'=>'Venta al por mayor de productos intermedios y desechos de origen textil'],
            ['codigo'=>'46693','actividad'=>'Venta al por mayor de productos intermedios y desechos de origen metálico'],
            ['codigo'=>'46694','actividad'=>'Venta al por mayor de productos intermedios y desechos de papel y cartón'],
            ['codigo'=>'46695','actividad'=>'Venta al por mayor fertilizantes, abonos, agroquímicos y productos similares'],
            ['codigo'=>'46696','actividad'=>'Venta al por mayor de productos intermedios y desechos de origen plástico'],
            ['codigo'=>'46697','actividad'=>'Venta al por mayor de tintas para imprenta, productos curtientes y materias y productos colorantes'],
            ['codigo'=>'46698','actividad'=>'Venta de productos intermedios y desechos de origen químico y de caucho'],
            ['codigo'=>'46699','actividad'=>'Venta al por mayor de productos intermedios y desechos ncp'],
            ['codigo'=>'46701','actividad'=>'Venta de algodón en oro'],
            ['codigo'=>'46900','actividad'=>'Venta al por mayor de otros productos'],
            ['codigo'=>'46901','actividad'=>'Venta al por mayor de cohetes y otros productos pirotécnicos'],
            ['codigo'=>'46902','actividad'=>'Venta al por mayor de artículos diversos para consumo humano'],
            ['codigo'=>'46903','actividad'=>'Venta al por mayor de armas de fuego, municiones y accesorios'],
            ['codigo'=>'46904','actividad'=>'Venta al por mayor de toldos y tiendas de campaña de cualquier material'],
            ['codigo'=>'46905','actividad'=>'Venta al por mayor de exhibidores publicitarios y rótulos'],
            ['codigo'=>'46906','actividad'=>'Venta al por mayor de artículos promocionales diversos'],
            ['codigo'=>'47111','actividad'=>'Venta en supermercados'],
            ['codigo'=>'47112','actividad'=>'Venta en tiendas de artículos de primera necesidad'],
            ['codigo'=>'47119','actividad'=>'Almacenes (venta de diversos artículos)'],
            ['codigo'=>'47190','actividad'=>'Venta al por menor de otros productos en comercios no especializados'],
            ['codigo'=>'47199','actividad'=>'Venta de establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas y tabaco'],
            ['codigo'=>'47211','actividad'=>'Venta al por menor de frutas y hortalizas'],
            ['codigo'=>'47212','actividad'=>'Venta al por menor de carnes, embutidos y productos de granja'],
            ['codigo'=>'47213','actividad'=>'Venta al por menor de pescado y mariscos'],
            ['codigo'=>'47214','actividad'=>'Venta al por menor de productos lácteos'],
            ['codigo'=>'47215','actividad'=>'Venta al por menor de productos de panadería, repostería y galletas'],
            ['codigo'=>'47216','actividad'=>'Venta al por menor de huevos'],
            ['codigo'=>'47217','actividad'=>'Venta al por menor de carnes y productos cárnicos'],
            ['codigo'=>'47218','actividad'=>'Venta al por menor de granos básicos y otros'],
            ['codigo'=>'47219','actividad'=>'Venta al por menor de alimentos n.c.p'],
            ['codigo'=>'47221','actividad'=>'Venta al por menor de hielo'],
            ['codigo'=>'47223','actividad'=>'Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento'],
            ['codigo'=>'47224','actividad'=>'Venta de bebidas alcohólicas, para su consumo fuera del establecimiento'],
            ['codigo'=>'47225','actividad'=>'Venta de bebidas alcohólicas para su consumo dentro del establecimiento'],
            ['codigo'=>'47230','actividad'=>'Venta al por menor de tabaco'],
            ['codigo'=>'47300','actividad'=>'Venta de combustibles, lubricantes y otros (gasolineras)'],
            ['codigo'=>'47411','actividad'=>'Venta al por menor de computadoras y equipo periférico'],
            ['codigo'=>'47412','actividad'=>'Venta de equipo y accesorios de telecomunicación'],
            
            ['codigo'=>'47420','actividad'=>'Venta al por menor de equipo de audio y video'],
            ['codigo'=>'47510','actividad'=>'Venta al por menor de hilados, tejidos y productos textiles de mercería; confecciones para el hogar y textiles n.c.p.'],
            ['codigo'=>'47521','actividad'=>'Venta al por menor de productos de madera'],
            ['codigo'=>'47522','actividad'=>'Venta al por menor de artículos de ferretería'],
            ['codigo'=>'47523','actividad'=>'Venta al por menor de productos de pinturerías'],
            ['codigo'=>'47524','actividad'=>'Venta al por menor en vidrierías'],
            ['codigo'=>'47529','actividad'=>'Venta al por menor de materiales de construcción y artículos conexos'],
            ['codigo'=>'47530','actividad'=>'Venta al por menor de tapices, alfombras y revestimientos de paredes y pisos en comercios especializados'],
            ['codigo'=>'47591','actividad'=>'Venta al por menor de muebles'],
            ['codigo'=>'47592','actividad'=>'Venta al por menor de artículos de bazar'],
            ['codigo'=>'47593','actividad'=>'Venta al por menor de aparatos electrodomésticos, repuestos y accesorios'],
            ['codigo'=>'47594','actividad'=>'Venta al por menor de artículos eléctricos y de iluminación'],
            ['codigo'=>'47598','actividad'=>'Venta al por menor de instrumentos musicales'],
            ['codigo'=>'47610','actividad'=>'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados'],
            ['codigo'=>'47620','actividad'=>'Venta al por menor de discos láser, cassettes, cintas de video y otros'],
            ['codigo'=>'47630','actividad'=>'Venta al por menor de productos y equipos de deporte'],
            ['codigo'=>'47631','actividad'=>'Venta al por menor de bicicletas, accesorios y repuestos'],
            ['codigo'=>'47640','actividad'=>'Venta al por menor de juegos y juguetes en comercios especializados'],
            ['codigo'=>'47711','actividad'=>'Venta al por menor de prendas de vestir y accesorios de vestir'],
            ['codigo'=>'47712','actividad'=>'Venta al por menor de calzado'],
            ['codigo'=>'47713','actividad'=>'Venta al por menor de artículos de peletería, marroquinería y talabartería'],
            ['codigo'=>'47721','actividad'=>'Venta al por menor de medicamentos farmacéuticos y otros materiales y artículos de uso médico, odontológico y veterinario'],
            ['codigo'=>'47722','actividad'=>'Venta al por menor de productos cosméticos y de tocador'],
            ['codigo'=>'47731','actividad'=>'Venta al por menor de productos de joyería, bisutería, óptica, relojería'],
            ['codigo'=>'47732','actividad'=>'Venta al por menor de plantas, semillas, animales y artículos conexos'],
            ['codigo'=>'47733','actividad'=>'Venta al por menor de combustibles de uso doméstico (gas propano y gas licuado)'],
            ['codigo'=>'47734','actividad'=>'Venta al por menor de artesanías, artículos cerámicos y recuerdos en general'],
            ['codigo'=>'47735','actividad'=>'Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos religiosos en general'],
            ['codigo'=>'47736','actividad'=>'Venta al por menor de armas de fuego, municiones y accesorios'],
            ['codigo'=>'47737','actividad'=>'Venta al por menor de artículos de cohetería y pirotécnicos'],
            ['codigo'=>'47738','actividad'=>'Venta al por menor de artículos desechables de uso personal y doméstico (servilletas, papel higiénico, pañales, toallas sanitarias, etc)'],
            ['codigo'=>'47739','actividad'=>'Venta al por menor de otros productos n.c.p.'],
            ['codigo'=>'47741','actividad'=>'Venta al por menor de artículos usados'],
            ['codigo'=>'47742','actividad'=>'Venta al por menor de textiles y confecciones usados'],
            ['codigo'=>'47743','actividad'=>'Venta al por menor de libros, revistas, papel y cartón usados'],
            ['codigo'=>'47749','actividad'=>'Venta al por menor de productos usados n.c.p.'],
            ['codigo'=>'47811','actividad'=>'Venta al por menor de frutas, verduras y hortalizas'],
            ['codigo'=>'47814','actividad'=>'Venta al por menor de productos lácteos'],
            ['codigo'=>'47815','actividad'=>'Venta al por menor de productos de panadería, galletas y similares'],
            ['codigo'=>'47816','actividad'=>'Venta al por menor de bebidas'],
            ['codigo'=>'47818','actividad'=>'Venta al por menor en tiendas de mercado y puestos'],
            ['codigo'=>'47821','actividad'=>'Venta al por menor de hilados, tejidos y productos textiles de mercería en puestos de mercados y ferias'],
            ['codigo'=>'47822','actividad'=>'Venta al por menor de artículos textiles excepto confecciones para el hogar en puestos de mercados y ferias'],
            ['codigo'=>'47823','actividad'=>'Venta al por menor de confecciones textiles para el hogar en puestos de mercados y ferias'],
            ['codigo'=>'47824','actividad'=>'Venta al por menor de prendas de vestir, accesorios de vestir y similares en puestos de mercados y ferias'],
            ['codigo'=>'47825','actividad'=>'Venta al por menor de ropa usada'],
            ['codigo'=>'47826','actividad'=>'Venta al por menor de calzado, artículos de marroquinería y talabartería en puestos de mercados y ferias'],
            ['codigo'=>'47827','actividad'=>'Venta al por menor de artículos de marroquinería y talabartería en puestos de mercados y ferias'],
            ['codigo'=>'47829','actividad'=>'Venta al por menor de artículos textiles ncp en puestos de mercados y ferias'],
            ['codigo'=>'47891','actividad'=>'Venta al por menor de animales, flores y productos conexos en puestos de feria y mercados'],
            ['codigo'=>'47892','actividad'=>'Venta al por menor de productos medicinales, cosméticos, de tocador y de limpieza en puestos de ferias y mercados'],
            ['codigo'=>'47893','actividad'=>'Venta al por menor de artículos de bazar en puestos de ferias y mercados'],
            ['codigo'=>'47894','actividad'=>'Venta al por menor de artículos de papel, envases, libros, revistas y conexos en puestos de feria y mercados'],
            ['codigo'=>'47895','actividad'=>'Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de feria y mercados'],
            ['codigo'=>'47896','actividad'=>'Venta al por menor de equipos accesorios para las comunicaciones en puestos de feria y mercados'],
            ['codigo'=>'47899','actividad'=>'Venta al por menor en puestos de ferias y mercados n.c.p.'],
            ['codigo'=>'47910','actividad'=>'Venta al por menor por correo o Internet'],
            ['codigo'=>'47990','actividad'=>'Otros tipos de venta al por menor no realizada, en almacenes, puestos de venta o mercado'],
            ['codigo'=>'49110','actividad'=>'Transporte interurbano de pasajeros por ferrocarril'],
            ['codigo'=>'49120','actividad'=>'Transporte de carga por ferrocarril'],
            ['codigo'=>'49211','actividad'=>'Transporte de pasajeros urbanos e interurbano mediante buses'],
            ['codigo'=>'49212','actividad'=>'Transporte de pasajeros interdepartamental mediante microbuses'],
            ['codigo'=>'49213','actividad'=>'Transporte de pasajeros urbanos e interurbano mediante microbuses'],
            ['codigo'=>'49214','actividad'=>'Transporte de pasajeros interdepartamental mediante buses'],
            ['codigo'=>'49221','actividad'=>'Transporte internacional de pasajeros'],
            ['codigo'=>'49222','actividad'=>'Transporte de pasajeros mediante taxis y autos con chofer'],
            ['codigo'=>'49223','actividad'=>'Transporte escolar'],
            ['codigo'=>'49225','actividad'=>'Transporte de pasajeros para excursiones'],
            ['codigo'=>'49226','actividad'=>'Servicios de transporte de personal'],
            ['codigo'=>'49229','actividad'=>'Transporte de pasajeros por vía terrestre ncp'],
            ['codigo'=>'49231','actividad'=>'Transporte de carga urbano'],
            ['codigo'=>'49232','actividad'=>'Transporte nacional de carga'],
            ['codigo'=>'49233','actividad'=>'Transporte de carga internacional'],
            ['codigo'=>'49234','actividad'=>'Servicios de mudanza'],
            ['codigo'=>'49235','actividad'=>'Alquiler de vehículos de carga con conductor'],
            ['codigo'=>'49300','actividad'=>'Transporte por oleoducto o gasoducto'],
            ['codigo'=>'50110','actividad'=>'Transporte de pasajeros marítimo y de cabotaje'],
            ['codigo'=>'50120','actividad'=>'Transporte de carga marítimo y de cabotaje'],
            ['codigo'=>'50211','actividad'=>'Transporte de pasajeros por vías de navegación interiores'],
            ['codigo'=>'50212','actividad'=>'Alquiler de equipo de transporte de pasajeros por vías de navegación interior con conductor'],
            ['codigo'=>'50220','actividad'=>'Transporte de carga por vías de navegación interiores'],
            ['codigo'=>'51100','actividad'=>'Transporte aéreo de pasajeros'],
            ['codigo'=>'51201','actividad'=>'Transporte de carga por vía aérea'],
            ['codigo'=>'51202','actividad'=>'Alquiler de equipo de aerotransporte con operadores para el propósito de transportar carga'],
            ['codigo'=>'52101','actividad'=>'Alquiler de instalaciones de almacenamiento en zonas francas'],
            ['codigo'=>'52102','actividad'=>'Alquiler de silos para conservación y almacenamiento de granos'],
            ['codigo'=>'52103','actividad'=>'Alquiler de instalaciones con refrigeración para almacenamiento y conservación de alimentos y otros productos'],
            ['codigo'=>'52109','actividad'=>'Alquiler de bodegas para almacenamiento y depósito n.c.p.'],
            ['codigo'=>'52211','actividad'=>'Servicio de garaje y estacionamiento'],
            ['codigo'=>'52212','actividad'=>'Servicios de terminales para el transporte por vía terrestre'],
            ['codigo'=>'52219','actividad'=>'Servicios para el transporte por vía terrestre n.c.p.'],
            ['codigo'=>'52220','actividad'=>'Servicios para el transporte acuático'],
            ['codigo'=>'52230','actividad'=>'Servicios para el transporte aéreo'],
            ['codigo'=>'52240','actividad'=>'Manipulación de carga'],
            ['codigo'=>'52290','actividad'=>'Servicios para el transporte ncp'],
            ['codigo'=>'52291','actividad'=>'Agencias de tramitaciones aduanales'],
            ['codigo'=>'53100','actividad'=>'Servicios de correo nacional'],
            ['codigo'=>'53200','actividad'=>'Actividades de correo distintas a las actividades postales nacionales'],
            ['codigo'=>'53201','actividad'=>'Agencia privada de correo y encomiendas'],
            ['codigo'=>'55101','actividad'=>'Actividades de alojamiento para estancias cortas'],
            ['codigo'=>'55102','actividad'=>'Hoteles'],
            ['codigo'=>'55200','actividad'=>'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas'],
            ['codigo'=>'55900','actividad'=>'Alojamiento n.c.p.'],
            ['codigo'=>'56101','actividad'=>'Restaurantes'],
            ['codigo'=>'56106','actividad'=>'Pupusería'],
            ['codigo'=>'56107','actividad'=>'Actividades varias de restaurantes'],
            ['codigo'=>'56108','actividad'=>'Comedores'],
            ['codigo'=>'56109','actividad'=>'Merenderos ambulantes'],
            ['codigo'=>'56210','actividad'=>'Preparación de comida para eventos especiales'],
            ['codigo'=>'56291','actividad'=>'Servicios de provisión de comidas por contrato'],
            ['codigo'=>'56292','actividad'=>'Servicios de concesión de cafetines y chalet en empresas'],
            ['codigo'=>'56299','actividad'=>'Servicios de preparación de comidas ncp'],
            ['codigo'=>'56301','actividad'=>'Servicio de expendio de bebidas en salones y bares'],
            ['codigo'=>'56302','actividad'=>'Servicio de expendio de bebidas en puestos callejeros, mercados y ferias'],
            ['codigo'=>'58110','actividad'=>'Edición de libros, folletos, partituras y otras ediciones distintas a estas'],
            ['codigo'=>'58120','actividad'=>'Edición de directorios y listas de correos'],
            ['codigo'=>'58130','actividad'=>'Edición de periódicos, revistas y otras publicaciones periódicas'],
            ['codigo'=>'58190','actividad'=>'Otras actividades de edición'],
            ['codigo'=>'58200','actividad'=>'Edición de programas informáticos (software)'],
            ['codigo'=>'59110','actividad'=>'Actividades de producción cinematográfica'],
            ['codigo'=>'59120','actividad'=>'Actividades de post producción de películas, videos y programas de televisión'],
            ['codigo'=>'59130','actividad'=>'Actividades de distribución de películas cinematográficas, videos y programas de televisión'],
            ['codigo'=>'59140','actividad'=>'Actividades de exhibición de películas cinematográficas y cintas de vídeo'],
            ['codigo'=>'59200','actividad'=>'Actividades de edición y grabación de música'],
            ['codigo'=>'60100','actividad'=>'Servicios de difusiones de radio'],
            ['codigo'=>'60201','actividad'=>'Actividades de programación y difusión de televisión abierta'],
            ['codigo'=>'60202','actividad'=>'Actividades de suscripción y difusión de televisión por cable y/o suscripción'],
            ['codigo'=>'60299','actividad'=>'Servicios de televisión, incluye televisión por cable'],
            ['codigo'=>'60900','actividad'=>'Programación y transmisión de radio y televisión'],
            ['codigo'=>'61101','actividad'=>'Servicio de telefonía'],
            ['codigo'=>'61102','actividad'=>'Servicio de Internet'],
            ['codigo'=>'61103','actividad'=>'Servicio de telefonía fija'],
            ['codigo'=>'61109','actividad'=>'Servicio de Internet n.c.p.'],
            ['codigo'=>'61201','actividad'=>'Servicios de telefonía celular'],
            ['codigo'=>'61202','actividad'=>'Servicios de Internet inalámbrico'],
            ['codigo'=>'61209','actividad'=>'Servicios de telecomunicaciones inalámbrico n.c.p.'],
            ['codigo'=>'61301','actividad'=>'Telecomunicaciones satelitales'],
            ['codigo'=>'61309','actividad'=>'Comunicación vía satélite n.c.p.'],
            ['codigo'=>'61900','actividad'=>'Actividades de telecomunicación n.c.p.'],
            ['codigo'=>'62010','actividad'=>'Programación Informática'],
            ['codigo'=>'62020','actividad'=>'Consultorías y gestión de servicios informáticos'],
            ['codigo'=>'62090','actividad'=>'Otras actividades de tecnología de información y servicios de computadora'],
            ['codigo'=>'63110','actividad'=>'Procesamiento de datos y actividades relacionadas'],
            ['codigo'=>'63120','actividad'=>'Portales WEB'],
            ['codigo'=>'63910','actividad'=>'Servicios de Agencias de Noticias'],
            ['codigo'=>'63990','actividad'=>'Otros servicios de información n.c.p.'],
            ['codigo'=>'64110','actividad'=>'Servicios provistos por el Banco Central de El Salvador'],
            ['codigo'=>'64190','actividad'=>'Bancos'],
            ['codigo'=>'64192','actividad'=>'Entidades dedicadas al envío de remesas'],
            ['codigo'=>'64199','actividad'=>'Otras entidades financieras'],
            ['codigo'=>'64200','actividad'=>'Actividades de sociedades de cartera'],
            ['codigo'=>'64300','actividad'=>'Fideicomisos, fondos y otras fuentes de financiamiento'],
            ['codigo'=>'64910','actividad'=>'Arrendamientos financieros'],
            ['codigo'=>'64920','actividad'=>'Asociaciones cooperativas de ahorro y crédito dedicadas a la intermediación financiera'],
            ['codigo'=>'64921','actividad'=>'Instituciones emisoras de tarjetas de crédito y otros'],
            ['codigo'=>'64922','actividad'=>'Tipos de crédito ncp'],
            ['codigo'=>'64928','actividad'=>'Prestamistas y casas de empeño'],
            ['codigo'=>'64990','actividad'=>'Actividades de servicios financieros, excepto la financiación de planes de seguros y de pensiones n.c.p.'],
            ['codigo'=>'65110','actividad'=>'Planes de seguros de vida'],
            ['codigo'=>'65120','actividad'=>'Planes de seguro excepto de vida'],
            ['codigo'=>'65199','actividad'=>'Seguros generales de todo tipo'],
            ['codigo'=>'65200','actividad'=>'Planes de seguro'],
            ['codigo'=>'65300','actividad'=>'Planes de pensiones'],
            ['codigo'=>'66110','actividad'=>'Administración de mercados financieros (Bolsa de Valores)'],
            ['codigo'=>'66120','actividad'=>'Actividades bursátiles (Corredores de Bolsa)'],
            ['codigo'=>'66190','actividad'=>'Actividades auxiliares de la intermediación financiera ncp'],
            ['codigo'=>'66210','actividad'=>'Evaluación de riesgos y daños'],
            ['codigo'=>'66220','actividad'=>'Actividades de agentes y corredores de seguros'],
            ['codigo'=>'66290','actividad'=>'Otras actividades auxiliares de seguros y fondos de pensiones'],
            ['codigo'=>'66300','actividad'=>'Actividades de administración de fondos'],
            ['codigo'=>'68101','actividad'=>'Servicio de alquiler y venta de lotes en cementerios'],
            ['codigo'=>'68109','actividad'=>'Actividades inmobiliarias realizadas con bienes propios o arrendados n.c.p.'],
            ['codigo'=>'68200','actividad'=>'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'],
            ['codigo'=>'69100','actividad'=>'Actividades jurídicas'],
            ['codigo'=>'69200','actividad'=>'Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos'],
            ['codigo'=>'70100','actividad'=>'Actividades de oficinas centrales de sociedades de cartera'],
            ['codigo'=>'70200','actividad'=>'Actividades de consultoría en gestión empresarial'],
            ['codigo'=>'71101','actividad'=>'Servicios de arquitectura y planificación urbana y servicios conexos'],
            ['codigo'=>'71102','actividad'=>'Servicios de ingeniería'],
            ['codigo'=>'71103','actividad'=>'Servicios de agrimensura, topografía, cartografía, prospección y geofísica y servicios conexos'],
            ['codigo'=>'71200','actividad'=>'Ensayos y análisis técnicos'],
            ['codigo'=>'72100','actividad'=>'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería'],
            ['codigo'=>'72199','actividad'=>'Investigaciones científicas'],
            ['codigo'=>'72200','actividad'=>'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades científica y desarrollo'],
            ['codigo'=>'73100','actividad'=>'Publicidad'],
            ['codigo'=>'73200','actividad'=>'Investigación de mercados y realización de encuestas de opinión pública'],
            ['codigo'=>'74100','actividad'=>'Actividades de diseño especializado'],
            ['codigo'=>'74200','actividad'=>'Actividades de fotografía'],
            ['codigo'=>'74900','actividad'=>'Servicios profesionales y científicos ncp'],
            ['codigo'=>'75000','actividad'=>'Actividades veterinarias'],
            ['codigo'=>'77101','actividad'=>'Alquiler de equipo de transporte terrestre'],
            ['codigo'=>'77102','actividad'=>'Alquiler de equipo de transporte acuático'],
            ['codigo'=>'77103','actividad'=>'Alquiler de equipo de transporte por vía aérea'],
            ['codigo'=>'77210','actividad'=>'Alquiler y arrendamiento de equipo de recreo y deportivo'],
            ['codigo'=>'77220','actividad'=>'Alquiler de cintas de video y discos'],
            ['codigo'=>'77290','actividad'=>'Alquiler de otros efectos personales y enseres domésticos'],
            ['codigo'=>'77300','actividad'=>'Alquiler de maquinaria y equipo'],
            ['codigo'=>'77400','actividad'=>'Arrendamiento de productos de propiedad intelectual'],
            ['codigo'=>'78100','actividad'=>'Obtención y dotación de personal'],
            ['codigo'=>'78200','actividad'=>'Actividades de las agencias de trabajo temporal'],
            ['codigo'=>'78300','actividad'=>'Dotación de recursos humanos y gestión; gestión de las funciones de recursos humanos'],
            ['codigo'=>'79110','actividad'=>'Actividades de agencias de viajes y organizadores de viajes; actividades de asistencia a turistas'],
            ['codigo'=>'79120','actividad'=>'Actividades de los operadores turísticos'],
            ['codigo'=>'79900','actividad'=>'Otros servicios de reservas y actividades relacionadas'],
            ['codigo'=>'80100','actividad'=>'Servicios de seguridad privados'],
            ['codigo'=>'80201','actividad'=>'Actividades de servicios de sistemas de seguridad'],
            ['codigo'=>'80202','actividad'=>'Actividades para la prestación de sistemas de seguridad'],
            ['codigo'=>'80300','actividad'=>'Actividades de investigación'],
            ['codigo'=>'81100','actividad'=>'Actividades combinadas de mantenimiento de edificios e instalaciones'],
            ['codigo'=>'81210','actividad'=>'Limpieza general de edificios'],
            ['codigo'=>'81290','actividad'=>'Otras actividades combinadas de mantenimiento de edificios e instalaciones ncp'],
            ['codigo'=>'81300','actividad'=>'Servicio de jardinería'],
            ['codigo'=>'82110','actividad'=>'Servicios administrativos de oficinas'],
            ['codigo'=>'82190','actividad'=>'Servicio de fotocopiado y similares, excepto en imprentas'],
            ['codigo'=>'82200','actividad'=>'Actividades de las centrales de llamadas (call center)'],
            ['codigo'=>'82300','actividad'=>'Organización de convenciones y ferias de negocios'],
            ['codigo'=>'82910','actividad'=>'Actividades de agencias de cobro y oficinas de crédito'],
            ['codigo'=>'82921','actividad'=>'Servicios de envase y empaque de productos alimenticios'],
            ['codigo'=>'82922','actividad'=>'Servicios de envase y empaque de productos medicinales'],
            ['codigo'=>'82929','actividad'=>'Servicio de envase y empaque ncp'],
            ['codigo'=>'82990','actividad'=>'Actividades de apoyo empresariales ncp'],
            ['codigo'=>'84110','actividad'=>'Actividades de la Administración Pública en general'],
            ['codigo'=>'84111','actividad'=>'Alcaldías Municipales'],
            ['codigo'=>'84120','actividad'=>'Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad social'],
            ['codigo'=>'84130','actividad'=>'Regulación y facilitación de la actividad económica'],
            ['codigo'=>'84210','actividad'=>'Actividades de administración y funcionamiento del Ministerio de Relaciones Exteriores'],
            ['codigo'=>'84220','actividad'=>'Actividades de defensa'],
            ['codigo'=>'84230','actividad'=>'Actividades de mantenimiento del orden público y de seguridad'],
            ['codigo'=>'84300','actividad'=>'Actividades de planes de seguridad social de afiliación obligatoria'],
            ['codigo'=>'85101','actividad'=>'Guardería educativa'],
            ['codigo'=>'85102','actividad'=>'Enseñanza preescolar o parvularia'],
            ['codigo'=>'85103','actividad'=>'Enseñanza primaria'],
            ['codigo'=>'85104','actividad'=>'Servicio de educación preescolar y primaria integrada'],
            ['codigo'=>'85211','actividad'=>'Enseñanza secundaria tercer ciclo (7°, 8° y 9°)'],
            ['codigo'=>'85212','actividad'=>'Enseñanza secundaria de formación general bachillerato'],
            ['codigo'=>'85221','actividad'=>'Enseñanza secundaria de formación técnica y profesional'],
            ['codigo'=>'85222','actividad'=>'Enseñanza secundaria de formación técnica y profesional integrada con enseñanza primaria'],
            ['codigo'=>'85301','actividad'=>'Enseñanza superior universitaria'],
            ['codigo'=>'85302','actividad'=>'Enseñanza superior no universitaria'],
            ['codigo'=>'85303','actividad'=>'Enseñanza superior integrada a educación secundaria y/o primaria'],
            ['codigo'=>'85410','actividad'=>'Educación deportiva y recreativa'],
            ['codigo'=>'85420','actividad'=>'Educación cultural'],
            ['codigo'=>'85490','actividad'=>'Otros tipos de enseñanza n.c.p.'],
            ['codigo'=>'85499','actividad'=>'Enseñanza formal'],
            ['codigo'=>'85500','actividad'=>'Servicios de apoyo a la enseñanza'],
            ['codigo'=>'86100','actividad'=>'Actividades de hospitales'],
            ['codigo'=>'86201','actividad'=>'Clínicas médicas'],
            ['codigo'=>'86202','actividad'=>'Servicios de Odontología'],
            ['codigo'=>'86203','actividad'=>'Servicios médicos'],
            ['codigo'=>'86901','actividad'=>'Servicios de análisis y estudios de diagnóstico'],
            ['codigo'=>'86902','actividad'=>'Actividades de atención a la salud humana'],
            ['codigo'=>'86909','actividad'=>'Otros servicios relacionados con la salud ncp'],
            ['codigo'=>'87100','actividad'=>'Residencias de ancianos con atención de enfermería'],
            ['codigo'=>'87200','actividad'=>'Instituciones dedicadas al tratamiento del retraso mental, problemas de salud mental y el uso indebido de sustancias nocivas'],
            ['codigo'=>'87300','actividad'=>'Instituciones dedicadas al cuidado de ancianos y discapacitados'],
            ['codigo'=>'87900','actividad'=>'Actividades de asistencia a niños y jóvenes'],
            ['codigo'=>'87901','actividad'=>'Otras actividades de atención en instituciones'],
            ['codigo'=>'88100','actividad'=>'Actividades de asistencia sociales sin alojamiento para ancianos y discapacitados'],
            ['codigo'=>'88900','actividad'=>'Servicios sociales sin alojamiento ncp'],
            ['codigo'=>'90000','actividad'=>'Actividades creativas artísticas y de esparcimiento'],
            ['codigo'=>'91010','actividad'=>'Actividades de bibliotecas y archivos'],
            ['codigo'=>'91020','actividad'=>'Actividades de museos y preservación de lugares y edificios históricos'],
            ['codigo'=>'91030','actividad'=>'Actividades de jardines botánicos, zoológicos y de reservas naturales'],
            ['codigo'=>'92000','actividad'=>'Actividades de juegos y apuestas'],
            ['codigo'=>'93110','actividad'=>'Gestión de instalaciones deportivas'],
            ['codigo'=>'93120','actividad'=>'Actividades de clubes deportivos'],
            ['codigo'=>'93190','actividad'=>'Otras actividades deportivas'],
            ['codigo'=>'93210','actividad'=>'Actividades de parques de atracciones y parques temáticos'],
            ['codigo'=>'93291','actividad'=>'Discotecas y salas de baile'],
            ['codigo'=>'93298','actividad'=>'Centros vacacionales'],
            ['codigo'=>'93299','actividad'=>'Actividades de esparcimiento ncp'],
            ['codigo'=>'94110','actividad'=>'Actividades de organizaciones empresariales y de empleadores'],
            ['codigo'=>'94120','actividad'=>'Actividades de organizaciones profesionales'],
            ['codigo'=>'94200','actividad'=>'Actividades de sindicatos'],
            ['codigo'=>'94910','actividad'=>'Actividades de organizaciones religiosas'],
            ['codigo'=>'94920','actividad'=>'Actividades de organizaciones políticas'],
            ['codigo'=>'94990','actividad'=>'Actividades de asociaciones n.c.p.'],
            ['codigo'=>'95110','actividad'=>'Reparación de computadoras y equipo periférico'],
            ['codigo'=>'95120','actividad'=>'Reparación de equipo de comunicación'],
            ['codigo'=>'95210','actividad'=>'Reparación de aparatos electrónicos de consumo'],
            ['codigo'=>'95220','actividad'=>'Reparación de aparatos doméstico y equipo de hogar y jardín'],
            ['codigo'=>'95230','actividad'=>'Reparación de calzado y artículos de cuero'],
            ['codigo'=>'95240','actividad'=>'Reparación de muebles y accesorios para el hogar'],
            ['codigo'=>'95291','actividad'=>'Reparación de instrumentos musicales'],
            ['codigo'=>'95292','actividad'=>'Servicios de cerrajería y copiado de llaves'],
            ['codigo'=>'95293','actividad'=>'Reparación de joyas y relojes'],
            ['codigo'=>'95294','actividad'=>'Reparación de bicicletas, sillas de ruedas y rodados n.c.p.'],
            ['codigo'=>'95294','actividad'=>'Reparación de enseres personales n.c.p.'],
            ['codigo'=>'96010','actividad'=>'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco'],
            ['codigo'=>'96020','actividad'=>'Peluquería y otros tratamientos de belleza'],
            ['codigo'=>'96030','actividad'=>'Pompas fúnebres y actividades conexas'],
            ['codigo'=>'96091','actividad'=>'Servicios de sauna y otros servicios para la estética corporal n.c.p.'],
            ['codigo'=>'96092','actividad'=>'Servicios n.c.p.'],
            ['codigo'=>'97000','actividad'=>'Actividad de los hogares en calidad de empleadores de personal doméstico'],
            ['codigo'=>'98100','actividad'=>'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio'],
            ['codigo'=>'98200','actividad'=>'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio'],
            ['codigo'=>'99000','actividad'=>'Actividades de organizaciones y órganos extraterritoriales'],
            ['codigo'=>'10001','actividad'=>'Empleados'],
            ['codigo'=>'10002','actividad'=>'Pensionado'],
            ['codigo'=>'10003','actividad'=>'Estudiante'],
            ['codigo'=>'10004','actividad'=>'Desempleado'],
            ['codigo'=>'10005','actividad'=>'Otros'],
            ['codigo'=>'10006','actividad'=>'Comerciante'],

            /*['codigo'=>'87900','actividad'=>'Actividades de asistencia social sin alojamiento'],
            ['codigo'=>'97000','actividad'=>'Actividades económicas'],
            ['codigo'=>'98100','actividad'=>'Actividades de los hogares como empleadores'],*/
        ];

        foreach ($actividades as $actividad) {
            actividades_economicas::firstOrCreate($actividad);
        }
    }
}
