<?php

namespace Database\Seeders;

use App\Models\municipios;
use Illuminate\Database\Seeder;


class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipios = [
            #Municipios de Ahuachapán
            ['municipio' => 'Ahuachapán Norte',   'codigo_postal' => '02101', 'codigo_mh' => '13', 'departamentos_id' => 1],
            ['municipio' => 'Ahuachapán Centro',  'codigo_postal' => '02101', 'codigo_mh' => '14', 'departamentos_id' => 1],
            ['municipio' => 'Ahuachapán Sur',     'codigo_postal' => '02101', 'codigo_mh' => '15', 'departamentos_id' => 1],
            #Municipios de Santa Ana
            ['municipio' => 'Santa Ana Norte',    'codigo_postal' => '02203', 'codigo_mh' => '14', 'departamentos_id' => 2],
            ['municipio' => 'Santa Ana Centro',   'codigo_postal' => '02203', 'codigo_mh' => '15', 'departamentos_id' => 2],
            ['municipio' => 'Santa Ana Este',     'codigo_postal' => '02203', 'codigo_mh' => '16', 'departamentos_id' => 2],
            ['municipio' => 'Santa Ana Oeste',    'codigo_postal' => '02203', 'codigo_mh' => '17', 'departamentos_id' => 2],
            #Municipios de Sonsonate
            ['municipio' => 'Sonsonate Norte',    'codigo_postal' => '02302', 'codigo_mh' => '17', 'departamentos_id' => 3],
            ['municipio' => 'Sonsonate Centro',   'codigo_postal' => '02302', 'codigo_mh' => '18', 'departamentos_id' => 3],
            ['municipio' => 'Sonsonate Este',     'codigo_postal' => '02302', 'codigo_mh' => '19', 'departamentos_id' => 3],
            ['municipio' => 'Sonsonate Oeste',    'codigo_postal' => '02302', 'codigo_mh' => '20', 'departamentos_id' => 3],
            #Municipios de Chalatenango
            ['municipio' => 'Chalatenango Norte', 'codigo_postal' => '01302', 'codigo_mh' => '34', 'departamentos_id' => 4],
            ['municipio' => 'Chalatenango Centro', 'codigo_postal' => '01302', 'codigo_mh' => '35', 'departamentos_id' => 4],
            ['municipio' => 'Chalatenango Sur',   'codigo_postal' => '01302', 'codigo_mh' => '36', 'departamentos_id' => 4],
            #Municipios de La Libertad
            ['municipio' => 'La Libertad Norte',  'codigo_postal' => '01502', 'codigo_mh' => '23', 'departamentos_id' => 5],
            ['municipio' => 'La Libertad Centro', 'codigo_postal' => '01502', 'codigo_mh' => '24', 'departamentos_id' => 5],
            ['municipio' => 'La Libertad Oeste',  'codigo_postal' => '01502', 'codigo_mh' => '25', 'departamentos_id' => 5],
            ['municipio' => 'La Libertad Este',   'codigo_postal' => '01502', 'codigo_mh' => '26', 'departamentos_id' => 5],
            ['municipio' => 'La Libertad Costa',  'codigo_postal' => '01502', 'codigo_mh' => '27', 'departamentos_id' => 5],
            ['municipio' => 'La Libertad Sur',    'codigo_postal' => '01502', 'codigo_mh' => '28', 'departamentos_id' => 5],
            #Municipios de San Salvador
            ['municipio' => 'San Salvador Norte', 'codigo_postal' => '01122', 'codigo_mh' => '20', 'departamentos_id' => 6],
            ['municipio' => 'San Salvador Oeste', 'codigo_postal' => '01122', 'codigo_mh' => '21', 'departamentos_id' => 6],
            ['municipio' => 'San Salvador Este',  'codigo_postal' => '01122', 'codigo_mh' => '22', 'departamentos_id' => 6],
            ['municipio' => 'San Salvador Centro', 'codigo_postal' => '01122', 'codigo_mh' => '23', 'departamentos_id' => 6],
            ['municipio' => 'San Salvador Sur',   'codigo_postal' => '01122', 'codigo_mh' => '24', 'departamentos_id' => 6],
            #Municipios de Cuscatlán
            ['municipio' => 'Cuscatlán Norte',    'codigo_postal' => '01401', 'codigo_mh' => '17', 'departamentos_id' => 7],
            ['municipio' => 'Cuscatlán Sur',      'codigo_postal' => '01401', 'codigo_mh' => '18', 'departamentos_id' => 7],
            #Municipios de La Paz
            ['municipio' => 'La Paz Oeste',       'codigo_postal' => '01603', 'codigo_mh' => '23', 'departamentos_id' => 8],
            ['municipio' => 'La Paz Centro',      'codigo_postal' => '01603', 'codigo_mh' => '24', 'departamentos_id' => 8],
            ['municipio' => 'La Paz Este',        'codigo_postal' => '01603', 'codigo_mh' => '25', 'departamentos_id' => 8],
            #Municipios de Cabañas
            ['municipio' => 'Cabañas Oeste',      'codigo_postal' => '01202', 'codigo_mh' => '10', 'departamentos_id' => 9],
            ['municipio' => 'Cabañas Este',       'codigo_postal' => '01202', 'codigo_mh' => '11', 'departamentos_id' => 9],
            #Municipios de San Vicente
            ['municipio' => 'San Vicente Norte',  'codigo_postal' => '01132', 'codigo_mh' => '14', 'departamentos_id' => 10],
            ['municipio' => 'San Vicente Sur',    'codigo_postal' => '01132', 'codigo_mh' => '15', 'departamentos_id' => 10],
            #Municipios de Usulután
            ['municipio' => 'Usulután Norte',     'codigo_postal' => '03404', 'codigo_mh' => '24', 'departamentos_id' => 11],
            ['municipio' => 'Usulután Este',      'codigo_postal' => '03404', 'codigo_mh' => '25', 'departamentos_id' => 11],
            ['municipio' => 'Usulután Oeste',     'codigo_postal' => '03404', 'codigo_mh' => '26', 'departamentos_id' => 11],
            #Municipios de San Miguel
            ['municipio' => 'San Miguel Norte',   'codigo_postal' => '03301', 'codigo_mh' => '21', 'departamentos_id' => 12],
            ['municipio' => 'San Miguel Centro',  'codigo_postal' => '03301', 'codigo_mh' => '22', 'departamentos_id' => 12],
            ['municipio' => 'San Miguel Oeste',   'codigo_postal' => '03301', 'codigo_mh' => '23', 'departamentos_id' => 12],
            #Municipios de Morazán
            ['municipio' => 'Morazán Norte',      'codigo_postal' => '03202', 'codigo_mh' => '27', 'departamentos_id' => 13],
            ['municipio' => 'Morazán Sur',        'codigo_postal' => '03202', 'codigo_mh' => '28', 'departamentos_id' => 13],
            #Municipios de La Unión
            ['municipio' => 'La Unión Norte',     'codigo_postal' => '03104', 'codigo_mh' => '19', 'departamentos_id' => 14],
            ['municipio' => 'La Unión Sur',       'codigo_postal' => '03104', 'codigo_mh' => '20', 'departamentos_id' => 14],

            #Municipios de Ahuachapán
            /*['municipio'=>'Ahuachapán',            'codigo_postal'=>'02101','codigo_mh'=>'01','departamentos_id'=>1],
            ['municipio'=>'Apaneca',               'codigo_postal'=>'02102','codigo_mh'=>'02','departamentos_id'=>1],
            ['municipio'=>'Atiquizaya',            'codigo_postal'=>'02103','codigo_mh'=>'03','departamentos_id'=>1],
            ['municipio'=>'Concepción de Ataco',   'codigo_postal'=>'02106','codigo_mh'=>'04','departamentos_id'=>1],
            ['municipio'=>'El Refugio',            'codigo_postal'=>'02107','codigo_mh'=>'05','departamentos_id'=>1],
            ['municipio'=>'Guaymango',             'codigo_postal'=>'02108','codigo_mh'=>'06','departamentos_id'=>1],
            ['municipio'=>'Jujutla',               'codigo_postal'=>'02109','codigo_mh'=>'07','departamentos_id'=>1],
            ['municipio'=>'San Francisco Menéndez','codigo_postal'=>'02113','codigo_mh'=>'08','departamentos_id'=>1],
            ['municipio'=>'San Lorenzo',           'codigo_postal'=>'02115','codigo_mh'=>'09','departamentos_id'=>1],
            ['municipio'=>'San Pedro Puxtla',      'codigo_postal'=>'02116','codigo_mh'=>'10','departamentos_id'=>1],
            ['municipio'=>'Tacuba',                'codigo_postal'=>'02117','codigo_mh'=>'11','departamentos_id'=>1],
            ['municipio'=>'Turín',                 'codigo_postal'=>'02128','codigo_mh'=>'12','departamentos_id'=>1],
            #Municipios de Santa Ana
            ['municipio'=>'Candelaria de la Frontera','codigo_postal'=>'02203','codigo_mh'=>'01','departamentos_id'=>2],
            ['municipio'=>'Coatepeque',               'codigo_postal'=>'02204','codigo_mh'=>'02','departamentos_id'=>2],
            ['municipio'=>'Chalchuapa',               'codigo_postal'=>'02205','codigo_mh'=>'03','departamentos_id'=>2],
            ['municipio'=>'El Congo',                 'codigo_postal'=>'02208','codigo_mh'=>'04','departamentos_id'=>2],
            ['municipio'=>'El Porvenir',              'codigo_postal'=>'02208','codigo_mh'=>'05','departamentos_id'=>2],
            ['municipio'=>'Masahuat',                 'codigo_postal'=>'02210','codigo_mh'=>'06','departamentos_id'=>2],
            ['municipio'=>'Metapán',                  'codigo_postal'=>'02211','codigo_mh'=>'07','departamentos_id'=>2],
            ['municipio'=>'San Antonio Pajonal',      'codigo_postal'=>'02212','codigo_mh'=>'08','departamentos_id'=>2],
            ['municipio'=>'San Sebastián Salitrillo', 'codigo_postal'=>'02215','codigo_mh'=>'09','departamentos_id'=>2],
            ['municipio'=>'Santa Ana',                'codigo_postal'=>'02205','codigo_mh'=>'10','departamentos_id'=>2],
            ['municipio'=>'Santa Rosa Guachipilín',   'codigo_postal'=>'02216','codigo_mh'=>'11','departamentos_id'=>2],
            ['municipio'=>'Santiago de la Frontera',  'codigo_postal'=>'02217','codigo_mh'=>'12','departamentos_id'=>2],
            ['municipio'=>'Texistepeque',             'codigo_postal'=>'02218','codigo_mh'=>'13','departamentos_id'=>2],
            #Municipios de Sonsonate
            ['municipio'=>'Acajutla',               'codigo_postal'=>'02302','codigo_mh'=>'01','departamentos_id'=>3],
            ['municipio'=>'Armenia',                'codigo_postal'=>'02303','codigo_mh'=>'02','departamentos_id'=>3],
            ['municipio'=>'Caluco',                 'codigo_postal'=>'02304','codigo_mh'=>'03','departamentos_id'=>3],
            ['municipio'=>'Cuisnahuat',             'codigo_postal'=>'02305','codigo_mh'=>'04','departamentos_id'=>3],
            ['municipio'=>'Santa Isabel Ishuatán',  'codigo_postal'=>'02318','codigo_mh'=>'05','departamentos_id'=>3],
            ['municipio'=>'Izalco',                 'codigo_postal'=>'02306','codigo_mh'=>'06','departamentos_id'=>3],
            ['municipio'=>'Juayúa',                 'codigo_postal'=>'02307','codigo_mh'=>'07','departamentos_id'=>3],
            ['municipio'=>'Nahuizalco',             'codigo_postal'=>'02311','codigo_mh'=>'08','departamentos_id'=>3],
            ['municipio'=>'Nahulingo',              'codigo_postal'=>'02312','codigo_mh'=>'09','departamentos_id'=>3],
            ['municipio'=>'Salcoatitán',            'codigo_postal'=>'02313','codigo_mh'=>'10','departamentos_id'=>3],
            ['municipio'=>'San Antonio del Monte',  'codigo_postal'=>'02314','codigo_mh'=>'11','departamentos_id'=>3],
            ['municipio'=>'San Julián',             'codigo_postal'=>'02316','codigo_mh'=>'12','departamentos_id'=>3],
            ['municipio'=>'Santa Catarina Masahuat','codigo_postal'=>'02317','codigo_mh'=>'13','departamentos_id'=>3],
            ['municipio'=>'Santo Domingo Guzmán',   'codigo_postal'=>'02319','codigo_mh'=>'14','departamentos_id'=>3],
            ['municipio'=>'Sonsonate',              'codigo_postal'=>'02301','codigo_mh'=>'15','departamentos_id'=>3],
            ['municipio'=>'Sonzacate',              'codigo_postal'=>'02320','codigo_mh'=>'16','departamentos_id'=>3],
            #Municipios de Chalatenango
            ['municipio'=>'Agua Caliente',           'codigo_postal'=>'01302','codigo_mh'=>'01','departamentos_id'=>4],
            ['municipio'=>'Arcatao',                 'codigo_postal'=>'01302','codigo_mh'=>'02','departamentos_id'=>4],
            ['municipio'=>'Azacualpa',               'codigo_postal'=>'01304','codigo_mh'=>'03','departamentos_id'=>4],
            ['municipio'=>'Citalá',                  'codigo_postal'=>'01306','codigo_mh'=>'04','departamentos_id'=>4],
            ['municipio'=>'Comalapa',                'codigo_postal'=>'01307','codigo_mh'=>'05','departamentos_id'=>4],
            ['municipio'=>'Concepción Quezaltepeque','codigo_postal'=>'01308','codigo_mh'=>'06','departamentos_id'=>4],
            ['municipio'=>'Chalatenango',            'codigo_postal'=>'01301','codigo_mh'=>'07','departamentos_id'=>4],
            ['municipio'=>'Dulce Nombre de María',   'codigo_postal'=>'01309','codigo_mh'=>'08','departamentos_id'=>4],
            ['municipio'=>'El Carrizal',             'codigo_postal'=>'01311','codigo_mh'=>'09','departamentos_id'=>4],
            ['municipio'=>'El Paraíso',              'codigo_postal'=>'01312','codigo_mh'=>'10','departamentos_id'=>4],
            ['municipio'=>'La Laguna',               'codigo_postal'=>'01313','codigo_mh'=>'11','departamentos_id'=>4],
            ['municipio'=>'La Palma',                'codigo_postal'=>'01314','codigo_mh'=>'12','departamentos_id'=>4],
            ['municipio'=>'La Reina',                'codigo_postal'=>'01315','codigo_mh'=>'13','departamentos_id'=>4],
            ['municipio'=>'Las Vueltas',             'codigo_postal'=>'01317','codigo_mh'=>'14','departamentos_id'=>4],
            ['municipio'=>'Nombre de Jesús',         'codigo_postal'=>'01318','codigo_mh'=>'15','departamentos_id'=>4],
            ['municipio'=>'Nueva Concepción',        'codigo_postal'=>'01319','codigo_mh'=>'16','departamentos_id'=>4],
            ['municipio'=>'Nueva Trinidad',          'codigo_postal'=>'01320','codigo_mh'=>'17','departamentos_id'=>4],
            ['municipio'=>'Ojos de Agua',            'codigo_postal'=>'01324','codigo_mh'=>'18','departamentos_id'=>4],
            ['municipio'=>'Potonico',                'codigo_postal'=>'01322','codigo_mh'=>'19','departamentos_id'=>4],
            ['municipio'=>'San Antonio de la Crúz',  'codigo_postal'=>'01326','codigo_mh'=>'20','departamentos_id'=>4],
            ['municipio'=>'San Antonio Los Ranchos', 'codigo_postal'=>'01325','codigo_mh'=>'21','departamentos_id'=>4],
            ['municipio'=>'San Fernando',            'codigo_postal'=>'01326','codigo_mh'=>'22','departamentos_id'=>4],
            ['municipio'=>'San Francisco Lempa',     'codigo_postal'=>'01327','codigo_mh'=>'23','departamentos_id'=>4],
            ['municipio'=>'San Francisco Morazán',   'codigo_postal'=>'01316','codigo_mh'=>'24','departamentos_id'=>4],
            ['municipio'=>'San Ignacio',             'codigo_postal'=>'01329','codigo_mh'=>'25','departamentos_id'=>4],
            ['municipio'=>'San Isidro Labrador',     'codigo_postal'=>'01330','codigo_mh'=>'26','departamentos_id'=>4],
            ['municipio'=>'San José Cancasque',      'codigo_postal'=>'01305','codigo_mh'=>'27','departamentos_id'=>4],
            ['municipio'=>'San José Las Flores',     'codigo_postal'=>'01316','codigo_mh'=>'28','departamentos_id'=>4],
            ['municipio'=>'San Luis del Carmen',     'codigo_postal'=>'01331','codigo_mh'=>'29','departamentos_id'=>4],
            ['municipio'=>'San Miguel de Mercedes',  'codigo_postal'=>'01332','codigo_mh'=>'30','departamentos_id'=>4],
            ['municipio'=>'San Rafael',              'codigo_postal'=>'01333','codigo_mh'=>'31','departamentos_id'=>4],
            ['municipio'=>'Santa Rita',              'codigo_postal'=>'01334','codigo_mh'=>'32','departamentos_id'=>4],
            ['municipio'=>'Tejutla',                 'codigo_postal'=>'01335','codigo_mh'=>'33','departamentos_id'=>4],
            #Municipios de La Libertad
            ['municipio'=>'Antiguo Cuscatlán',  'codigo_postal'=>'01502','codigo_mh'=>'01','departamentos_id'=>5],
            ['municipio'=>'Ciudad Arce',        'codigo_postal'=>'01504','codigo_mh'=>'02','departamentos_id'=>5],
            ['municipio'=>'Colón',              'codigo_postal'=>'01512','codigo_mh'=>'03','departamentos_id'=>5],
            ['municipio'=>'Comasagua',          'codigo_postal'=>'01506','codigo_mh'=>'04','departamentos_id'=>5],
            ['municipio'=>'Chiltiupán',         'codigo_postal'=>'01507','codigo_mh'=>'05','departamentos_id'=>5],
            ['municipio'=>'Huizúcar',           'codigo_postal'=>'01508','codigo_mh'=>'06','departamentos_id'=>5],
            ['municipio'=>'Jayaque',            'codigo_postal'=>'01509','codigo_mh'=>'07','departamentos_id'=>5],
            ['municipio'=>'Jicalapa',           'codigo_postal'=>'01510','codigo_mh'=>'08','departamentos_id'=>5],
            ['municipio'=>'La Libertad',        'codigo_postal'=>'01511','codigo_mh'=>'09','departamentos_id'=>5],
            ['municipio'=>'Nuevo Cuscatlán',    'codigo_postal'=>'01513','codigo_mh'=>'10','departamentos_id'=>5],
            ['municipio'=>'Santa Tecla',        'codigo_postal'=>'01501','codigo_mh'=>'11','departamentos_id'=>5],
            ['municipio'=>'Quezaltepeque',      'codigo_postal'=>'01515','codigo_mh'=>'12','departamentos_id'=>5],
            ['municipio'=>'Sacacoyo',           'codigo_postal'=>'01516','codigo_mh'=>'13','departamentos_id'=>5],
            ['municipio'=>'San José Villanueva','codigo_postal'=>'01517','codigo_mh'=>'14','departamentos_id'=>5],
            ['municipio'=>'San Juan Opico',     'codigo_postal'=>'01514','codigo_mh'=>'15','departamentos_id'=>5],
            ['municipio'=>'San Matías',         'codigo_postal'=>'01518','codigo_mh'=>'16','departamentos_id'=>5],
            ['municipio'=>'San Pablo Tacachico','codigo_postal'=>'01519','codigo_mh'=>'17','departamentos_id'=>5],
            ['municipio'=>'Tamanique',          'codigo_postal'=>'01522','codigo_mh'=>'18','departamentos_id'=>5],
            ['municipio'=>'Talnique',           'codigo_postal'=>'01521','codigo_mh'=>'19','departamentos_id'=>5],
            ['municipio'=>'Teotepeque',         'codigo_postal'=>'01523','codigo_mh'=>'20','departamentos_id'=>5],
            ['municipio'=>'Tepecoyo',           'codigo_postal'=>'01524','codigo_mh'=>'21','departamentos_id'=>5],
            ['municipio'=>'Zaragoza',           'codigo_postal'=>'01525','codigo_mh'=>'22','departamentos_id'=>5],
            #Municipios de San Salvador
            ['municipio'=>'Aguilares',           'codigo_postal'=>'01122','codigo_mh'=>'01','departamentos_id'=>6],
            ['municipio'=>'Apopa',               'codigo_postal'=>'01123','codigo_mh'=>'02','departamentos_id'=>6],
            ['municipio'=>'Ayutuxtepeque',       'codigo_postal'=>'01121','codigo_mh'=>'03','departamentos_id'=>6],
            ['municipio'=>'Cuscatancingo',       'codigo_postal'=>'01119','codigo_mh'=>'04','departamentos_id'=>6],
            ['municipio'=>'El Paisnal',          'codigo_postal'=>'01124','codigo_mh'=>'05','departamentos_id'=>6],
            ['municipio'=>'Guazapa',             'codigo_postal'=>'01124','codigo_mh'=>'06','departamentos_id'=>6],
            ['municipio'=>'Ilopango',            'codigo_postal'=>'01117','codigo_mh'=>'07','departamentos_id'=>6],
            ['municipio'=>'Mejicanos',           'codigo_postal'=>'01120','codigo_mh'=>'08','departamentos_id'=>6],
            ['municipio'=>'Nejapa',              'codigo_postal'=>'01126','codigo_mh'=>'09','departamentos_id'=>6],
            ['municipio'=>'Panchimalco',         'codigo_postal'=>'01127','codigo_mh'=>'10','departamentos_id'=>6],
            ['municipio'=>'Rosario de Mora',     'codigo_postal'=>'01128','codigo_mh'=>'11','departamentos_id'=>6],
            ['municipio'=>'San Marcos',          'codigo_postal'=>'01115','codigo_mh'=>'12','departamentos_id'=>6],
            ['municipio'=>'San Martín',          'codigo_postal'=>'01129','codigo_mh'=>'13','departamentos_id'=>6],
            ['municipio'=>'San Salvador',        'codigo_postal'=>'01101','codigo_mh'=>'14','departamentos_id'=>6],
            ['municipio'=>'Santiago Texacuangos','codigo_postal'=>'01130','codigo_mh'=>'15','departamentos_id'=>6],
            ['municipio'=>'Santo Tomás',         'codigo_postal'=>'01131','codigo_mh'=>'16','departamentos_id'=>6],
            ['municipio'=>'Soyapango',           'codigo_postal'=>'01116','codigo_mh'=>'17','departamentos_id'=>6],
            ['municipio'=>'Tonacatepeque',       'codigo_postal'=>'01132','codigo_mh'=>'18','departamentos_id'=>6],
            ['municipio'=>'Ciudad Delgado',      'codigo_postal'=>'01118','codigo_mh'=>'19','departamentos_id'=>6],
            #Municipios de Cuscatlan
            ['municipio'=>'Candelaria',             'codigo_postal'=>'01302','codigo_mh'=>'01','departamentos_id'=>7],
            ['municipio'=>'Cojutepeque',            'codigo_postal'=>'01401','codigo_mh'=>'02','departamentos_id'=>7],
            ['municipio'=>'El Carmen',              'codigo_postal'=>'01403','codigo_mh'=>'03','departamentos_id'=>7],
            ['municipio'=>'El Rosario',             'codigo_postal'=>'01404','codigo_mh'=>'04','departamentos_id'=>7],
            ['municipio'=>'Monte San Juan',         'codigo_postal'=>'01406','codigo_mh'=>'05','departamentos_id'=>7],
            ['municipio'=>'Oratorio de Concepción', 'codigo_postal'=>'01406','codigo_mh'=>'06','departamentos_id'=>7],
            ['municipio'=>'San Bartolomé Perulapía','codigo_postal'=>'01407','codigo_mh'=>'07','departamentos_id'=>7],
            ['municipio'=>'San Cristóbal',          'codigo_postal'=>'01408','codigo_mh'=>'08','departamentos_id'=>7],
            ['municipio'=>'San José Guayabal',      'codigo_postal'=>'01409','codigo_mh'=>'09','departamentos_id'=>7],
            ['municipio'=>'San Pedro Perulapán',    'codigo_postal'=>'01410','codigo_mh'=>'10','departamentos_id'=>7],
            ['municipio'=>'San Rafael Cedros',      'codigo_postal'=>'01411','codigo_mh'=>'11','departamentos_id'=>7],
            ['municipio'=>'San Ramón',              'codigo_postal'=>'01412','codigo_mh'=>'12','departamentos_id'=>7],
            ['municipio'=>'Santa Crúz Analquito',   'codigo_postal'=>'01413','codigo_mh'=>'13','departamentos_id'=>7],
            ['municipio'=>'Santa Crúz Michapa',     'codigo_postal'=>'01414','codigo_mh'=>'14','departamentos_id'=>7],
            ['municipio'=>'Suchitoto',              'codigo_postal'=>'01415','codigo_mh'=>'15','departamentos_id'=>7],
            ['municipio'=>'Tenancingo',             'codigo_postal'=>'01416','codigo_mh'=>'16','departamentos_id'=>7],
            #Municipios de La Paz
            ['municipio'=>'Cuyultitán',             'codigo_postal'=>'01603','codigo_mh'=>'01','departamentos_id'=>8],
            ['municipio'=>'El Rosario',             'codigo_postal'=>'01604','codigo_mh'=>'02','departamentos_id'=>8],
            ['municipio'=>'Jerusalén',              'codigo_postal'=>'01605','codigo_mh'=>'03','departamentos_id'=>8],
            ['municipio'=>'Mercedes La Ceiba',      'codigo_postal'=>'01607','codigo_mh'=>'04','departamentos_id'=>8],
            ['municipio'=>'Olocuilta',              'codigo_postal'=>'01608','codigo_mh'=>'05','departamentos_id'=>8],
            ['municipio'=>'Paraíso de Osorio',      'codigo_postal'=>'01609','codigo_mh'=>'06','departamentos_id'=>8],
            ['municipio'=>'San Antonio Masahuat',   'codigo_postal'=>'01610','codigo_mh'=>'07','departamentos_id'=>8],
            ['municipio'=>'San Emigdio',            'codigo_postal'=>'01611','codigo_mh'=>'08','departamentos_id'=>8],
            ['municipio'=>'San Francisco Chinameca','codigo_postal'=>'01612','codigo_mh'=>'09','departamentos_id'=>8],
            ['municipio'=>'San Juan Nonualco',      'codigo_postal'=>'01613','codigo_mh'=>'10','departamentos_id'=>8],
            ['municipio'=>'San Juan Talpa',         'codigo_postal'=>'01614','codigo_mh'=>'11','departamentos_id'=>8],
            ['municipio'=>'San Juan Tepezontes',    'codigo_postal'=>'01615','codigo_mh'=>'12','departamentos_id'=>8],
            ['municipio'=>'San Luis Talpa',         'codigo_postal'=>'01616','codigo_mh'=>'13','departamentos_id'=>8],
            ['municipio'=>'San Miguel Tepezontes',  'codigo_postal'=>'01617','codigo_mh'=>'14','departamentos_id'=>8],
            ['municipio'=>'San Pedro Masahuat',     'codigo_postal'=>'01618','codigo_mh'=>'15','departamentos_id'=>8],
            ['municipio'=>'San Pedro Nonualco',     'codigo_postal'=>'01619','codigo_mh'=>'16','departamentos_id'=>8],
            ['municipio'=>'San Rafael Obrajuelo',   'codigo_postal'=>'01620','codigo_mh'=>'17','departamentos_id'=>8],
            ['municipio'=>'Santa María Ostuma',     'codigo_postal'=>'01621','codigo_mh'=>'18','departamentos_id'=>8],
            ['municipio'=>'Santiago Nonualco',      'codigo_postal'=>'01622','codigo_mh'=>'19','departamentos_id'=>8],
            ['municipio'=>'Tapalhuaca',             'codigo_postal'=>'01623','codigo_mh'=>'20','departamentos_id'=>8],
            ['municipio'=>'Zacatecoluca',           'codigo_postal'=>'01623','codigo_mh'=>'21','departamentos_id'=>8],
            ['municipio'=>'San Luis La Herradura',  'codigo_postal'=>'01606','codigo_mh'=>'22','departamentos_id'=>8],
            #Municipios de Cabañas
            ['municipio'=>'Cinquera',     'codigo_postal'=>'01202','codigo_mh'=>'01','departamentos_id'=>9],
            ['municipio'=>'Guacotecti',   'codigo_postal'=>'01203','codigo_mh'=>'02','departamentos_id'=>9],
            ['municipio'=>'Ilobasco',     'codigo_postal'=>'01204','codigo_mh'=>'03','departamentos_id'=>9],
            ['municipio'=>'Jutiapa',      'codigo_postal'=>'01208','codigo_mh'=>'04','departamentos_id'=>9],
            ['municipio'=>'San Isidro',   'codigo_postal'=>'01207','codigo_mh'=>'05','departamentos_id'=>9],
            ['municipio'=>'Sensuntepeque','codigo_postal'=>'01201','codigo_mh'=>'06','departamentos_id'=>9],
            ['municipio'=>'Tejutepeque',  'codigo_postal'=>'01208','codigo_mh'=>'07','departamentos_id'=>9],
            ['municipio'=>'Victoria',     'codigo_postal'=>'01210','codigo_mh'=>'08','departamentos_id'=>9],
            ['municipio'=>'Dolores',      'codigo_postal'=>'01209','codigo_mh'=>'09','departamentos_id'=>9],
            #Municipios de San Vicente
            ['municipio'=>'Apastepeque',           'codigo_postal'=>'01132','codigo_mh'=>'01','departamentos_id'=>10],
            ['municipio'=>'Guadalupe',             'codigo_postal'=>'01133','codigo_mh'=>'02','departamentos_id'=>10],
            ['municipio'=>'San Cayetano Istepeque','codigo_postal'=>'01134','codigo_mh'=>'03','departamentos_id'=>10],
            ['municipio'=>'Santa Clara',           'codigo_postal'=>'01139','codigo_mh'=>'04','departamentos_id'=>10],
            ['municipio'=>'Santo Domingo',         'codigo_postal'=>'01710','codigo_mh'=>'05','departamentos_id'=>10],
            ['municipio'=>'San Esteban Catarina',  'codigo_postal'=>'01135','codigo_mh'=>'06','departamentos_id'=>10],
            ['municipio'=>'San Ildefonso',         'codigo_postal'=>'01136','codigo_mh'=>'07','departamentos_id'=>10],
            ['municipio'=>'San Lorenzo',           'codigo_postal'=>'01137','codigo_mh'=>'08','departamentos_id'=>10],
            ['municipio'=>'San Sebastián',         'codigo_postal'=>'01131','codigo_mh'=>'09','departamentos_id'=>10],
            ['municipio'=>'San Vicente',           'codigo_postal'=>'01131','codigo_mh'=>'10','departamentos_id'=>10],
            ['municipio'=>'Tecoluca',              'codigo_postal'=>'01711','codigo_mh'=>'11','departamentos_id'=>10],
            ['municipio'=>'Tepetitán',             'codigo_postal'=>'01712','codigo_mh'=>'12','departamentos_id'=>10],
            ['municipio'=>'Verapaz',               'codigo_postal'=>'01713','codigo_mh'=>'13','departamentos_id'=>10],
            #Municipios de Usulutan
            ['municipio'=>'Alegría',             'codigo_postal'=>'03404','codigo_mh'=>'01','departamentos_id'=>11],
            ['municipio'=>'Berlín',              'codigo_postal'=>'03403','codigo_mh'=>'02','departamentos_id'=>11],
            ['municipio'=>'California',          'codigo_postal'=>'03404','codigo_mh'=>'03','departamentos_id'=>11],
            ['municipio'=>'Concepción Batres',   'codigo_postal'=>'03405','codigo_mh'=>'04','departamentos_id'=>11],
            ['municipio'=>'El Triunfo',          'codigo_postal'=>'03406','codigo_mh'=>'05','departamentos_id'=>11],
            ['municipio'=>'Ereguayquín',         'codigo_postal'=>'03407','codigo_mh'=>'06','departamentos_id'=>11],
            ['municipio'=>'Estanzuelas',         'codigo_postal'=>'03408','codigo_mh'=>'07','departamentos_id'=>11],
            ['municipio'=>'Jiquilisco',          'codigo_postal'=>'03409','codigo_mh'=>'08','departamentos_id'=>11],
            ['municipio'=>'Jucuapa',             'codigo_postal'=>'03410','codigo_mh'=>'09','departamentos_id'=>11],
            ['municipio'=>'Jucuarán',            'codigo_postal'=>'03411','codigo_mh'=>'10','departamentos_id'=>11],
            ['municipio'=>'Mercedes Umaña',      'codigo_postal'=>'03412','codigo_mh'=>'11','departamentos_id'=>11],
            ['municipio'=>'Nueva Granada',       'codigo_postal'=>'03413','codigo_mh'=>'12','departamentos_id'=>11],
            ['municipio'=>'Ozatlán',             'codigo_postal'=>'03415','codigo_mh'=>'13','departamentos_id'=>11],
            ['municipio'=>'Puerto El Triunfo',   'codigo_postal'=>'03417','codigo_mh'=>'14','departamentos_id'=>11],
            ['municipio'=>'San Agustín',         'codigo_postal'=>'03418','codigo_mh'=>'15','departamentos_id'=>11],
            ['municipio'=>'San Buenaventura',    'codigo_postal'=>'03409','codigo_mh'=>'16','departamentos_id'=>11],
            ['municipio'=>'San Dionisio',        'codigo_postal'=>'03420','codigo_mh'=>'17','departamentos_id'=>11],
            ['municipio'=>'Santa Elena',         'codigo_postal'=>'03422','codigo_mh'=>'18','departamentos_id'=>11],
            ['municipio'=>'San Francisco Javier','codigo_postal'=>'03421','codigo_mh'=>'19','departamentos_id'=>11],
            ['municipio'=>'Santa María',         'codigo_postal'=>'03423','codigo_mh'=>'20','departamentos_id'=>11],
            ['municipio'=>'Santiago de María',   'codigo_postal'=>'03424','codigo_mh'=>'21','departamentos_id'=>11],
            ['municipio'=>'Tecapán',             'codigo_postal'=>'03426','codigo_mh'=>'22','departamentos_id'=>11],
            ['municipio'=>'Usulután',            'codigo_postal'=>'03401','codigo_mh'=>'23','departamentos_id'=>11],
            #Municipios de San Miguel
            ['municipio'=>'Carolina',              'codigo_postal'=>'03302','codigo_mh'=>'01','departamentos_id'=>12],
            ['municipio'=>'Ciudad Barrios',        'codigo_postal'=>'03303','codigo_mh'=>'02','departamentos_id'=>12],
            ['municipio'=>'Comacarán',             'codigo_postal'=>'03304','codigo_mh'=>'03','departamentos_id'=>12],
            ['municipio'=>'Chapeltique',           'codigo_postal'=>'03305','codigo_mh'=>'04','departamentos_id'=>12],
            ['municipio'=>'Chinameca',             'codigo_postal'=>'03306','codigo_mh'=>'05','departamentos_id'=>12],
            ['municipio'=>'Chirilagua',            'codigo_postal'=>'03307','codigo_mh'=>'06','departamentos_id'=>12],
            ['municipio'=>'El Tránsito',           'codigo_postal'=>'03309','codigo_mh'=>'07','departamentos_id'=>12],
            ['municipio'=>'Lolotique',             'codigo_postal'=>'03311','codigo_mh'=>'08','departamentos_id'=>12],
            ['municipio'=>'Moncagua',              'codigo_postal'=>'03312','codigo_mh'=>'09','departamentos_id'=>12],
            ['municipio'=>'Nueva Guadalupe',       'codigo_postal'=>'03313','codigo_mh'=>'10','departamentos_id'=>12],
            ['municipio'=>'Nuevo Edén de San Juan','codigo_postal'=>'03314','codigo_mh'=>'11','departamentos_id'=>12],
            ['municipio'=>'Quelepa',               'codigo_postal'=>'03315','codigo_mh'=>'12','departamentos_id'=>12],
            ['municipio'=>'San Antonio del Mosco', 'codigo_postal'=>'03316','codigo_mh'=>'13','departamentos_id'=>12],
            ['municipio'=>'San Gerardo',           'codigo_postal'=>'03318','codigo_mh'=>'14','departamentos_id'=>12],
            ['municipio'=>'San Jorge',             'codigo_postal'=>'03319','codigo_mh'=>'15','departamentos_id'=>12],
            ['municipio'=>'San Luis de la Reina',  'codigo_postal'=>'03320','codigo_mh'=>'16','departamentos_id'=>12],
            ['municipio'=>'San Miguel',            'codigo_postal'=>'03301','codigo_mh'=>'17','departamentos_id'=>12],
            ['municipio'=>'San Rafael Oriente',    'codigo_postal'=>'03322','codigo_mh'=>'18','departamentos_id'=>12],
            ['municipio'=>'Sesori',                'codigo_postal'=>'03323','codigo_mh'=>'19','departamentos_id'=>12],
            ['municipio'=>'Uluazapa',              'codigo_postal'=>'03324','codigo_mh'=>'20','departamentos_id'=>12],
            #Municipios de Morazan
            ['municipio'=>'Arambala',              'codigo_postal'=>'03202','codigo_mh'=>'01','departamentos_id'=>13],
            ['municipio'=>'Cacaopera',             'codigo_postal'=>'03216','codigo_mh'=>'02','departamentos_id'=>13],
            ['municipio'=>'Corinto',               'codigo_postal'=>'03204','codigo_mh'=>'03','departamentos_id'=>13],
            ['municipio'=>'Chilanga',              'codigo_postal'=>'03203','codigo_mh'=>'04','departamentos_id'=>13],
            ['municipio'=>'Delicias de Concepción','codigo_postal'=>'03206','codigo_mh'=>'05','departamentos_id'=>13],
            ['municipio'=>'El Divisadero',         'codigo_postal'=>'03207','codigo_mh'=>'06','departamentos_id'=>13],
            ['municipio'=>'El Rosario',            'codigo_postal'=>'03208','codigo_mh'=>'07','departamentos_id'=>13],
            ['municipio'=>'Gualococti',            'codigo_postal'=>'03209','codigo_mh'=>'08','departamentos_id'=>13],
            ['municipio'=>'Guatajiagua',           'codigo_postal'=>'03210','codigo_mh'=>'09','departamentos_id'=>13],
            ['municipio'=>'Joateca',               'codigo_postal'=>'03211','codigo_mh'=>'10','departamentos_id'=>13],
            ['municipio'=>'Jocoaitique',           'codigo_postal'=>'03212','codigo_mh'=>'11','departamentos_id'=>13],
            ['municipio'=>'Jocoro',                'codigo_postal'=>'03213','codigo_mh'=>'12','departamentos_id'=>13],
            ['municipio'=>'Lolotiquillo',          'codigo_postal'=>'03214','codigo_mh'=>'13','departamentos_id'=>13],
            ['municipio'=>'Meanguera',             'codigo_postal'=>'03215','codigo_mh'=>'14','departamentos_id'=>13],
            ['municipio'=>'Osicala',               'codigo_postal'=>'03216','codigo_mh'=>'15','departamentos_id'=>13],
            ['municipio'=>'Perquín',               'codigo_postal'=>'03217','codigo_mh'=>'16','departamentos_id'=>13],
            ['municipio'=>'San Carlos',            'codigo_postal'=>'03218','codigo_mh'=>'17','departamentos_id'=>13],
            ['municipio'=>'San Fernando',          'codigo_postal'=>'03219','codigo_mh'=>'18','departamentos_id'=>13],
            ['municipio'=>'San Francisco Gotera',  'codigo_postal'=>'03201','codigo_mh'=>'19','departamentos_id'=>13],
            ['municipio'=>'San Isidro',            'codigo_postal'=>'03220','codigo_mh'=>'20','departamentos_id'=>13],
            ['municipio'=>'San Simón',             'codigo_postal'=>'03221','codigo_mh'=>'21','departamentos_id'=>13],
            ['municipio'=>'Sensembra',             'codigo_postal'=>'03222','codigo_mh'=>'22','departamentos_id'=>13],
            ['municipio'=>'Sociedad',              'codigo_postal'=>'03223','codigo_mh'=>'23','departamentos_id'=>13],
            ['municipio'=>'Torola',                'codigo_postal'=>'03224','codigo_mh'=>'24','departamentos_id'=>13],
            ['municipio'=>'Yamabal',               'codigo_postal'=>'03225','codigo_mh'=>'25','departamentos_id'=>13],
            ['municipio'=>'Yoloaiquín',            'codigo_postal'=>'03226','codigo_mh'=>'26','departamentos_id'=>13],
            #Municipios de La Union
            ['municipio'=>'Anamorós',             'codigo_postal'=>'03104','codigo_mh'=>'01','departamentos_id'=>14],
            ['municipio'=>'Bolívar',              'codigo_postal'=>'03105','codigo_mh'=>'02','departamentos_id'=>14],
            ['municipio'=>'Concepción de Oriente','codigo_postal'=>'03106','codigo_mh'=>'03','departamentos_id'=>14],
            ['municipio'=>'Conchagua',            'codigo_postal'=>'03107','codigo_mh'=>'04','departamentos_id'=>14],
            ['municipio'=>'El Carmen',            'codigo_postal'=>'03108','codigo_mh'=>'05','departamentos_id'=>14],
            ['municipio'=>'El Sauce',             'codigo_postal'=>'03109','codigo_mh'=>'06','departamentos_id'=>14],
            ['municipio'=>'Intipucá',             'codigo_postal'=>'03111','codigo_mh'=>'07','departamentos_id'=>14],
            ['municipio'=>'La Unión',             'codigo_postal'=>'03101','codigo_mh'=>'08','departamentos_id'=>14],
            ['municipio'=>'Lislique',             'codigo_postal'=>'03112','codigo_mh'=>'09','departamentos_id'=>14],
            ['municipio'=>'Meanguera del Golfo',  'codigo_postal'=>'03113','codigo_mh'=>'10','departamentos_id'=>14],
            ['municipio'=>'Nueva Esparta',        'codigo_postal'=>'03114','codigo_mh'=>'11','departamentos_id'=>14],
            ['municipio'=>'Pasaquina',            'codigo_postal'=>'03116','codigo_mh'=>'12','departamentos_id'=>14],
            ['municipio'=>'Polorós',              'codigo_postal'=>'03117','codigo_mh'=>'13','departamentos_id'=>14],
            ['municipio'=>'San Alejo',            'codigo_postal'=>'03119','codigo_mh'=>'14','departamentos_id'=>14],
            ['municipio'=>'San José',             'codigo_postal'=>'03120','codigo_mh'=>'15','departamentos_id'=>14],
            ['municipio'=>'Santa Rosa de Lima',   'codigo_postal'=>'03121','codigo_mh'=>'16','departamentos_id'=>14],
            ['municipio'=>'Yayantique',           'codigo_postal'=>'03122','codigo_mh'=>'17','departamentos_id'=>14],
            ['municipio'=>'Yucuaiquin',           'codigo_postal'=>'03123','codigo_mh'=>'18','departamentos_id'=>14],*/
        ];

        foreach ($municipios as $municipio) municipios::firstOrCreate($municipio);
    }
}
