<?php

namespace Database\Seeders;

use App\Models\paises;
use Illuminate\Database\Seeder;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['pais' => 'El Salvador',                           'codigo_mh' => 'SV', 'nacionalidad' => 'Salvadoreña'],
            ['pais' => 'Afganistán',                            'codigo_mh' => 'AF', 'nacionalidad' => 'Afgana'],
            ['pais' => 'Aland',                                 'codigo_mh' => 'AX', 'nacionalidad' => ''],
            ['pais' => 'Albania',                               'codigo_mh' => 'AL', 'nacionalidad' => 'Albanesa'],
            ['pais' => 'Alemania',                              'codigo_mh' => 'DE', 'nacionalidad' => 'Alemana'],
            ['pais' => 'Andorra',                               'codigo_mh' => 'AD', 'nacionalidad' => 'Andorrana'],
            ['pais' => 'Angola',                                'codigo_mh' => 'AO', 'nacionalidad' => 'Angoleña'],
            ['pais' => 'Anguila',                               'codigo_mh' => 'AI', 'nacionalidad' => 'Angoleña'],
            ['pais' => 'Antártica',                             'codigo_mh' => 'AQ', 'nacionalidad' => ''],
            ['pais' => 'Antigua y Barbuda',                     'codigo_mh' => 'AG', 'nacionalidad' => 'Antiguana y Barbudana'],
            ['pais' => 'Aruba',                                 'codigo_mh' => 'AW', 'nacionalidad' => 'Arubenses'],
            ['pais' => 'Arabia Saudita',                        'codigo_mh' => 'SA', 'nacionalidad' => 'Saudí'],
            ['pais' => 'Argelia',                               'codigo_mh' => 'DZ', 'nacionalidad' => 'Argelina'],
            ['pais' => 'Argentina',                             'codigo_mh' => 'AR', 'nacionalidad' => 'Argentina'],
            ['pais' => 'Armenia',                               'codigo_mh' => 'AM', 'nacionalidad' => 'Armenia'],
            ['pais' => 'Australia',                             'codigo_mh' => 'AU', 'nacionalidad' => 'Australiana'],
            ['pais' => 'Austria',                               'codigo_mh' => 'AT', 'nacionalidad' => 'Austríaca'],
            ['pais' => 'Azerbaiyán',                            'codigo_mh' => 'AZ', 'nacionalidad' => 'Azerbaiyana'],
            ['pais' => 'Bahamas',                               'codigo_mh' => 'BS', 'nacionalidad' => 'Bahameña'],
            ['pais' => 'Bahréin',                               'codigo_mh' => 'BH', 'nacionalidad' => 'Bareiní'],
            ['pais' => 'Bangladesh',                            'codigo_mh' => 'BD', 'nacionalidad' => 'Bangladesí'],
            ['pais' => 'Barbados',                              'codigo_mh' => 'BB', 'nacionalidad' => 'Barbadense'],
            ['pais' => 'Bélgica',                               'codigo_mh' => 'BE', 'nacionalidad' => 'Belga'],
            ['pais' => 'Belice',                                'codigo_mh' => 'BZ', 'nacionalidad' => 'Beliceña'],
            ['pais' => 'Benín',                                 'codigo_mh' => 'BJ', 'nacionalidad' => 'Beninés'],
            ['pais' => 'Bermudas',                              'codigo_mh' => 'BM', 'nacionalidad' => 'Bermudenses'],
            ['pais' => 'Bielorrusia',                           'codigo_mh' => 'BY', 'nacionalidad' => 'Bielorrusa'],
            ['pais' => 'Bolivia',                               'codigo_mh' => 'BO', 'nacionalidad' => 'Boliviana'],
            ['pais' => 'Bonaire, Sint Eustatius And Saba',      'codigo_mh' => 'BQ', 'nacionalidad' => 'Boinarenses'],
            ['pais' => 'Bosnia - Herzegovina',                  'codigo_mh' => 'BA', 'nacionalidad' => 'Bosnia'],
            ['pais' => 'Botswana',                              'codigo_mh' => 'BW', 'nacionalidad' => 'Botsuana'],
            ['pais' => 'Brasil',                                'codigo_mh' => 'BR', 'nacionalidad' => 'Brasileña'],
            ['pais' => 'Brunéi',                                'codigo_mh' => 'BN', 'nacionalidad' => 'Bruneana'],
            ['pais' => 'Bulgaria',                              'codigo_mh' => 'BG', 'nacionalidad' => 'Búlgara'],
            ['pais' => 'Burkina Faso',                          'codigo_mh' => 'BF', 'nacionalidad' => 'Burkinesa'],
            ['pais' => 'Burundi',                               'codigo_mh' => 'BI', 'nacionalidad' => 'Burundesa'],
            ['pais' => 'Bután',                                 'codigo_mh' => 'BT', 'nacionalidad' => 'Butanesa'],
            ['pais' => 'Cabo Verde',                            'codigo_mh' => 'CV', 'nacionalidad' => 'Cabo Verdiana'],
            ['pais' => 'Caimán, Islas',                         'codigo_mh' => 'KY', 'nacionalidad' => ''],
            ['pais' => 'Camboya',                               'codigo_mh' => 'KH', 'nacionalidad' => 'Camboyana'],
            ['pais' => 'Camerún',                               'codigo_mh' => 'CM', 'nacionalidad' => 'Camerunesa'],
            ['pais' => 'Canadá',                                'codigo_mh' => 'CA', 'nacionalidad' => 'Canadiense'],
            ['pais' => 'Centroafricana, República',             'codigo_mh' => 'CF', 'nacionalidad' => 'Centroafricana'],
            ['pais' => 'Chad',                                  'codigo_mh' => 'TD', 'nacionalidad' => 'Chadiana'],
            ['pais' => 'Chile',                                 'codigo_mh' => 'CL', 'nacionalidad' => 'Chilena'],
            ['pais' => 'China',                                 'codigo_mh' => 'CN', 'nacionalidad' => 'China'],
            ['pais' => 'Chipre',                                'codigo_mh' => 'CY', 'nacionalidad' => 'Chipriota'],
            ['pais' => 'Ciudad del Vaticano',                   'codigo_mh' => 'VA', 'nacionalidad' => 'Vaticana'],
            ['pais' => 'Colombia',                              'codigo_mh' => 'CO', 'nacionalidad' => 'Colombiana'],
            ['pais' => 'Comoras',                               'codigo_mh' => 'KM', 'nacionalidad' => 'Comorense'],
            ['pais' => 'Congo',                                 'codigo_mh' => 'CG', 'nacionalidad' => 'Congoleña'],
            ['pais' => 'Costa de Marfil',                       'codigo_mh' => 'CI', 'nacionalidad' => 'Marfileña'],
            ['pais' => 'Costa Rica',                            'codigo_mh' => 'CR', 'nacionalidad' => 'Costarricense'],
            ['pais' => 'Croacia',                               'codigo_mh' => 'HR', 'nacionalidad' => 'Croata'],
            ['pais' => 'Cuba',                                  'codigo_mh' => 'CU', 'nacionalidad' => 'Cubana'],
            ['pais' => 'Curazao',                               'codigo_mh' => 'CW', 'nacionalidad' => ''],
            ['pais' => 'Dinamarca',                             'codigo_mh' => 'DK', 'nacionalidad' => 'Danesa'],
            ['pais' => 'Dominica',                              'codigo_mh' => 'DM', 'nacionalidad' => 'Dominiquesa'],
            ['pais' => 'Djibouti',                              'codigo_mh' => 'DJ', 'nacionalidad' => ''],
            ['pais' => 'Ecuador',                               'codigo_mh' => 'EC', 'nacionalidad' => 'Ecuatoriana'],
            ['pais' => 'Egipto',                                'codigo_mh' => 'EG', 'nacionalidad' => 'Egipcia'],
            ['pais' => 'Emiratos Árabes Unidos',                'codigo_mh' => 'AE', 'nacionalidad' => 'Emiratí'],
            ['pais' => 'Eritrea',                               'codigo_mh' => 'ER', 'nacionalidad' => 'Eritrea'],
            ['pais' => 'Eslovaquia',                            'codigo_mh' => 'SK', 'nacionalidad' => 'Eslovaca'],
            ['pais' => 'Eslovenia',                             'codigo_mh' => 'SI', 'nacionalidad' => 'Eslovena'],
            ['pais' => 'España',                                'codigo_mh' => 'ES', 'nacionalidad' => 'Española'],
            ['pais' => 'Estados Unidos',                        'codigo_mh' => 'US', 'nacionalidad' => 'Estadounidense'],
            ['pais' => 'Estonia',                               'codigo_mh' => 'EE', 'nacionalidad' => 'Estonia'],
            ['pais' => 'Etiopía',                               'codigo_mh' => 'ET', 'nacionalidad' => 'Etíope'],
            ['pais' => 'Fiji',                                  'codigo_mh' => 'FJ', 'nacionalidad' => 'Fijiana'],
            ['pais' => 'Filipinas',                             'codigo_mh' => 'PH', 'nacionalidad' => 'Filipina'],
            ['pais' => 'Finlandia',                             'codigo_mh' => 'FI', 'nacionalidad' => 'Finlandesa'],
            ['pais' => 'Francia',                               'codigo_mh' => 'FR', 'nacionalidad' => 'Francesa'],
            ['pais' => 'Gabón',                                 'codigo_mh' => 'GA', 'nacionalidad' => 'Gabonesa'],
            ['pais' => 'Gambia',                                'codigo_mh' => 'GM', 'nacionalidad' => 'Gambiana'],
            ['pais' => 'Georgia',                               'codigo_mh' => 'GE', 'nacionalidad' => 'Georgiana'],
            ['pais' => 'Ghana',                                 'codigo_mh' => 'GH', 'nacionalidad' => 'Ghanesa'],
            ['pais' => 'Gibraltar',                             'codigo_mh' => 'GI', 'nacionalidad' => ''],
            ['pais' => 'Granada',                               'codigo_mh' => 'GD', 'nacionalidad' => 'Granadina'],
            ['pais' => 'Grecia',                                'codigo_mh' => 'GR', 'nacionalidad' => 'Griega'],
            ['pais' => 'Groenlandia',                           'codigo_mh' => 'GL', 'nacionalidad' => ''],
            ['pais' => 'Guadalupe',                             'codigo_mh' => 'GP', 'nacionalidad' => ''],
            ['pais' => 'Guam',                                  'codigo_mh' => 'GU', 'nacionalidad' => ''],
            ['pais' => 'Guatemala',                             'codigo_mh' => 'GT', 'nacionalidad' => 'Guatemalteca'],
            ['pais' => 'Guayana Francesa',                      'codigo_mh' => 'GF', 'nacionalidad' => ''],
            ['pais' => 'Guernsey',                              'codigo_mh' => 'GG', 'nacionalidad' => ''],
            ['pais' => 'Guinea',                                'codigo_mh' => 'GN', 'nacionalidad' => 'Guineana'],
            ['pais' => 'Guinea Ecuatorial',                     'codigo_mh' => 'GQ', 'nacionalidad' => 'Ecuatoguineana'],
            ['pais' => 'Guinea - Bissau',                       'codigo_mh' => 'GW', 'nacionalidad' => 'Guineana'],
            ['pais' => 'Guyana',                                'codigo_mh' => 'GY', 'nacionalidad' => 'Guyanesa'],
            ['pais' => 'Haití',                                 'codigo_mh' => 'HT', 'nacionalidad' => 'Haitiana'],
            ['pais' => 'Honduras',                              'codigo_mh' => 'HN', 'nacionalidad' => 'Hondureña'],
            ['pais' => 'Hong Kong',                             'codigo_mh' => 'HK', 'nacionalidad' => ''],
            ['pais' => 'Hungría',                               'codigo_mh' => 'HU', 'nacionalidad' => 'Húngara'],
            ['pais' => 'India',                                 'codigo_mh' => 'IN', 'nacionalidad' => 'India'],
            ['pais' => 'Indonesia',                             'codigo_mh' => 'ID', 'nacionalidad' => 'Indonesia'],
            ['pais' => 'Irak',                                  'codigo_mh' => 'IQ', 'nacionalidad' => 'Iraquí'],
            ['pais' => 'Irlanda',                               'codigo_mh' => 'IE', 'nacionalidad' => 'Irlandesa'],
            ['pais' => 'Isla Bouvet',                           'codigo_mh' => 'BV', 'nacionalidad' => ''],
            ['pais' => 'Isla de Man',                           'codigo_mh' => 'IM', 'nacionalidad' => ''],
            ['pais' => 'Isla Norfolk',                          'codigo_mh' => 'NF', 'nacionalidad' => ''],
            ['pais' => 'Islandia',                              'codigo_mh' => 'IS', 'nacionalidad' => 'Islandesa'],
            ['pais' => 'Islas Navidad',                         'codigo_mh' => 'CX', 'nacionalidad' => ''],
            ['pais' => 'Isla Cocos',                            'codigo_mh' => 'CC', 'nacionalidad' => ''],
            ['pais' => 'Islas Cook',                            'codigo_mh' => 'CK', 'nacionalidad' => ''],
            ['pais' => 'Islas Faroe',                           'codigo_mh' => 'FO', 'nacionalidad' => ''],
            ['pais' => 'Islas Georgias d. S. - Sandwich d. S.', 'codigo_mh' => 'GS', 'nacionalidad' => ''],
            ['pais' => 'Islas Heard y McDonald',                'codigo_mh' => 'HM', 'nacionalidad' => ''],
            ['pais' => 'Islas Malvinas (Falkland)',             'codigo_mh' => 'FK', 'nacionalidad' => ''],
            ['pais' => 'Islas Marianas del Norte',              'codigo_mh' => 'MP', 'nacionalidad' => ''],
            ['pais' => 'Islas Marshall',                        'codigo_mh' => 'MH', 'nacionalidad' => 'Marshalesa'],
            ['pais' => 'Islas Pitcairn',                        'codigo_mh' => 'PN', 'nacionalidad' => ''],
            ['pais' => 'Islas Turcas y Caicos',                 'codigo_mh' => 'TC', 'nacionalidad' => 'Turcos'],
            ['pais' => 'Islas Ultramarinas de EE.UU',           'codigo_mh' => 'UM', 'nacionalidad' => ''],
            ['pais' => 'Islas Vírgenes',                        'codigo_mh' => 'VI', 'nacionalidad' => ''],
            ['pais' => 'Israel',                                'codigo_mh' => 'IL', 'nacionalidad' => 'Israelí'],
            ['pais' => 'Italia',                                'codigo_mh' => 'IT', 'nacionalidad' => 'Italiana'],
            ['pais' => 'Jamaica',                               'codigo_mh' => 'JM', 'nacionalidad' => 'Jamaicana'],
            ['pais' => 'Japón',                                 'codigo_mh' => 'JP', 'nacionalidad' => 'Japonesa'],
            ['pais' => 'Jersey',                                'codigo_mh' => 'JE', 'nacionalidad' => ''],
            ['pais' => 'Jordania',                              'codigo_mh' => 'JO', 'nacionalidad' => 'Jordana'],
            ['pais' => 'Kazajistán',                            'codigo_mh' => 'KZ', 'nacionalidad' => 'Kazaja'],
            ['pais' => 'Kenia',                                 'codigo_mh' => 'KE', 'nacionalidad' => 'Keniana'],
            ['pais' => 'Kirguistán',                            'codigo_mh' => 'KG', 'nacionalidad' => 'Kirguisa'],
            ['pais' => 'Kiribati',                              'codigo_mh' => 'KI', 'nacionalidad' => 'Kiribatiana'],
            ['pais' => 'Kuwait',                                'codigo_mh' => 'KW', 'nacionalidad' => 'Kuwaití'],
            ['pais' => 'Laos, República Democrática',           'codigo_mh' => 'LA', 'nacionalidad' => 'Laosiana'],
            ['pais' => 'Lesotho',                               'codigo_mh' => 'LS', 'nacionalidad' => 'Lesotense'],
            ['pais' => 'Letonia',                               'codigo_mh' => 'LV', 'nacionalidad' => 'Letona'],
            ['pais' => 'Líbano',                                'codigo_mh' => 'LB', 'nacionalidad' => 'Libanesa'],
            ['pais' => 'Liberia',                               'codigo_mh' => 'LR', 'nacionalidad' => 'Liberiana'],
            ['pais' => 'Libia',                                 'codigo_mh' => 'LY', 'nacionalidad' => 'Libia'],
            ['pais' => 'Liechtenstein',                         'codigo_mh' => 'LI', 'nacionalidad' => 'Liechtensteiniana'],
            ['pais' => 'Lituania',                              'codigo_mh' => 'LT', 'nacionalidad' => 'Lituana'],
            ['pais' => 'Luxemburgo',                            'codigo_mh' => 'LU', 'nacionalidad' => 'Luxemburguesa'],
            ['pais' => 'Macao',                                 'codigo_mh' => 'MO', 'nacionalidad' => ''],
            ['pais' => 'Macedonia',                             'codigo_mh' => 'MK', 'nacionalidad' => ''],
            ['pais' => 'Madagascar',                            'codigo_mh' => 'MG', 'nacionalidad' => 'Malgache'],
            ['pais' => 'Malasia',                               'codigo_mh' => 'MY', 'nacionalidad' => 'Malaya'],
            ['pais' => 'Malawi',                                'codigo_mh' => 'MW', 'nacionalidad' => 'Malauí'],
            ['pais' => 'Maldivas',                              'codigo_mh' => 'MV', 'nacionalidad' => 'Maldiva'],
            ['pais' => 'Malí',                                  'codigo_mh' => 'ML', 'nacionalidad' => 'Maliense'],
            ['pais' => 'Malta',                                 'codigo_mh' => 'MT', 'nacionalidad' => 'Maltesa'],
            ['pais' => 'Marruecos',                             'codigo_mh' => 'MA', 'nacionalidad' => 'Marroquí'],
            ['pais' => 'Martinica e.a',                         'codigo_mh' => 'MQ', 'nacionalidad' => ''],
            ['pais' => 'Mauricio',                              'codigo_mh' => 'MU', 'nacionalidad' => 'Mauriciana'],
            ['pais' => 'Mauritania',                            'codigo_mh' => 'MR', 'nacionalidad' => 'Mauritana'],
            ['pais' => 'Mayotte',                               'codigo_mh' => 'YT', 'nacionalidad' => ''],
            ['pais' => 'México',                                'codigo_mh' => 'MX', 'nacionalidad' => 'Mexicana'],
            ['pais' => 'Micronesia',                            'codigo_mh' => 'FM', 'nacionalidad' => 'Micronesia'],
            ['pais' => 'Moldavia',                              'codigo_mh' => 'MD', 'nacionalidad' => 'Moldava'],
            ['pais' => 'Mónaco',                                'codigo_mh' => 'MC', 'nacionalidad' => 'Monegasca'],
            ['pais' => 'Mongolia',                              'codigo_mh' => 'MN', 'nacionalidad' => 'Mongola'],
            ['pais' => 'Montenegro',                            'codigo_mh' => 'ME', 'nacionalidad' => 'Montenegrina'],
            ['pais' => 'Montserrat',                            'codigo_mh' => 'MS', 'nacionalidad' => ''],
            ['pais' => 'Mozambique',                            'codigo_mh' => 'MZ', 'nacionalidad' => 'Mozambiqueña'],
            ['pais' => 'Myanmar',                               'codigo_mh' => 'MM', 'nacionalidad' => ''],
            ['pais' => 'Namibia',                               'codigo_mh' => 'NA', 'nacionalidad' => 'Namibia'],
            ['pais' => 'Nauru',                                 'codigo_mh' => 'NR', 'nacionalidad' => 'Nauruana'],
            ['pais' => 'Nepal',                                 'codigo_mh' => 'NP', 'nacionalidad' => 'Nepalí'],
            ['pais' => 'Nicaragua',                             'codigo_mh' => 'NI', 'nacionalidad' => 'Nicaragüense'],
            ['pais' => 'Níger',                                 'codigo_mh' => 'NE', 'nacionalidad' => 'Nigerina'],
            ['pais' => 'Nigeria',                               'codigo_mh' => 'NG', 'nacionalidad' => 'Nigeriana'],
            ['pais' => 'Niue',                                  'codigo_mh' => 'NU', 'nacionalidad' => ''],
            ['pais' => 'Noruega',                               'codigo_mh' => 'NO', 'nacionalidad' => 'Noruega'],
            ['pais' => 'Nueva Caledonia',                       'codigo_mh' => 'NC', 'nacionalidad' => ''],
            ['pais' => 'Nueva Zelanda',                         'codigo_mh' => 'NZ', 'nacionalidad' => 'Neozelandesa'],
            ['pais' => 'Omán',                                  'codigo_mh' => 'OM', 'nacionalidad' => 'Omaní'],
            ['pais' => 'Países Bajos',                          'codigo_mh' => 'NL', 'nacionalidad' => ''],
            ['pais' => 'Pakistán',                              'codigo_mh' => 'PK', 'nacionalidad' => 'Pakistaní'],
            ['pais' => 'Palaos',                                'codigo_mh' => 'PW', 'nacionalidad' => 'Palauana'],
            ['pais' => 'Palestina',                             'codigo_mh' => 'PS', 'nacionalidad' => ''],
            ['pais' => 'Panamá',                                'codigo_mh' => 'PA', 'nacionalidad' => 'Panameña'],
            ['pais' => 'Papúa, Nueva Guinea',                   'codigo_mh' => 'PG', 'nacionalidad' => 'Papuana'],
            ['pais' => 'Paraguay',                              'codigo_mh' => 'PY', 'nacionalidad' => 'Paraguaya'],
            ['pais' => 'Perú',                                  'codigo_mh' => 'PE', 'nacionalidad' => 'Peruana'],
            ['pais' => 'Polinesia Francesa',                    'codigo_mh' => 'PF', 'nacionalidad' => ''],
            ['pais' => 'Polonia',                               'codigo_mh' => 'PL', 'nacionalidad' => 'Polaca'],
            ['pais' => 'Portugal',                              'codigo_mh' => 'PT', 'nacionalidad' => 'Portuguesa'],
            ['pais' => 'Puerto Rico',                           'codigo_mh' => 'PR', 'nacionalidad' => 'Puertoriquenses'],
            ['pais' => 'Qatar',                                 'codigo_mh' => 'QA', 'nacionalidad' => 'Qatarí'],
            ['pais' => 'Reino Unido',                           'codigo_mh' => 'GB', 'nacionalidad' => 'Británica'],
            ['pais' => 'República Democrática Popular de Corea', 'codigo_mh' => 'KP', 'nacionalidad' => 'Coreana'],
            ['pais' => 'República Checa',                       'codigo_mh' => 'CZ', 'nacionalidad' => 'Checa'],
            ['pais' => 'República de Corea',                    'codigo_mh' => 'KR', 'nacionalidad' => 'Coreana'],
            ['pais' => 'República Democrática del Congo',       'codigo_mh' => 'CD', 'nacionalidad' => 'Congoleña'],
            ['pais' => 'República Dominicana',                  'codigo_mh' => 'DO', 'nacionalidad' => 'Dominicana'],
            ['pais' => 'República Islámica de Irán',            'codigo_mh' => 'IR', 'nacionalidad' => 'Iraní'],
            ['pais' => 'Reunión',                               'codigo_mh' => 'RE', 'nacionalidad' => ''],
            ['pais' => 'Ruanda',                                'codigo_mh' => 'RW', 'nacionalidad' => 'Ruandesa'],
            ['pais' => 'Rumania',                               'codigo_mh' => 'RO', 'nacionalidad' => 'Rumana'],
            ['pais' => 'Rusia',                                 'codigo_mh' => 'RU', 'nacionalidad' => 'Rusa'],
            ['pais' => 'Sahara Occidental',                     'codigo_mh' => 'EH', 'nacionalidad' => ''],
            ['pais' => 'Saint Barthélemy',                      'codigo_mh' => 'BL', 'nacionalidad' => ''],
            ['pais' => 'Saint Martin (French part)',            'codigo_mh' => 'MF', 'nacionalidad' => ''],
            ['pais' => 'Salomón Islas',                         'codigo_mh' => 'SB', 'nacionalidad' => 'Salomonense'],
            ['pais' => 'Samoa',                                 'codigo_mh' => 'WS', 'nacionalidad' => ''],
            ['pais' => 'Samoa Americana',                       'codigo_mh' => 'AS', 'nacionalidad' => ''],
            ['pais' => 'San Cristóbal y Nieves',                'codigo_mh' => 'KN', 'nacionalidad' => ''],
            ['pais' => 'San Marino',                            'codigo_mh' => 'SM', 'nacionalidad' => 'Sanmarinense'],
            ['pais' => 'San Pedro y Miquelón',                  'codigo_mh' => 'PM', 'nacionalidad' => ''],
            ['pais' => 'San Vicente y las Granadinas',          'codigo_mh' => 'VC', 'nacionalidad' => 'Sanvicentina y Granadinense'],
            ['pais' => 'Santa Elena',                           'codigo_mh' => 'SH', 'nacionalidad' => ''],
            ['pais' => 'Santa Lucía',                           'codigo_mh' => 'LC', 'nacionalidad' => 'Santa Lucense'],
            ['pais' => 'Santo Tomé y Príncipe',                 'codigo_mh' => 'ST', 'nacionalidad' => 'Santotomense'],
            ['pais' => 'Senegal',                               'codigo_mh' => 'SN', 'nacionalidad' => 'Senegalés'],
            ['pais' => 'Serbia',                                'codigo_mh' => 'RS', 'nacionalidad' => 'Serbia'],
            ['pais' => 'Seychelles',                            'codigo_mh' => 'SC', 'nacionalidad' => 'Seychellense'],
            ['pais' => 'Sierra Leona',                          'codigo_mh' => 'SL', 'nacionalidad' => 'Sierraleonés'],
            ['pais' => 'Singapur',                              'codigo_mh' => 'SG', 'nacionalidad' => 'Singapurense'],
            ['pais' => 'San Maarten (Dutch part)',              'codigo_mh' => 'SX', 'nacionalidad' => ''],
            ['pais' => 'Siria',                                 'codigo_mh' => 'SY', 'nacionalidad' => 'Siria'],
            ['pais' => 'Somalia',                               'codigo_mh' => 'SO', 'nacionalidad' => 'Somalí'],
            ['pais' => 'South Sudán',                           'codigo_mh' => 'SS', 'nacionalidad' => 'Sudanesa'],
            ['pais' => 'Sri Lanka',                             'codigo_mh' => 'LK', 'nacionalidad' => 'Ceilandesa'],
            ['pais' => 'Sudáfricana',                           'codigo_mh' => 'ZA', 'nacionalidad' => 'Sudafricana'],
            ['pais' => 'Sudán',                                 'codigo_mh' => 'SD', 'nacionalidad' => 'Sursudanesa'],
            ['pais' => 'Suecia',                                'codigo_mh' => 'SE', 'nacionalidad' => 'Sueca'],
            ['pais' => 'Suiza',                                 'codigo_mh' => 'CH', 'nacionalidad' => 'Suiza'],
            ['pais' => 'Surinám',                               'codigo_mh' => 'SR', 'nacionalidad' => 'Surinamesa'],
            ['pais' => 'Svalbard y Jan Mayen',                  'codigo_mh' => 'SJ', 'nacionalidad' => ''],
            ['pais' => 'Swazilandia',                           'codigo_mh' => 'SZ', 'nacionalidad' => ''],
            ['pais' => 'Tailandia',                             'codigo_mh' => 'TH', 'nacionalidad' => 'Tailandesa'],
            ['pais' => 'Taiwán, Provincia de China',            'codigo_mh' => 'TW', 'nacionalidad' => ''],
            ['pais' => 'Tanzania, República Unida',             'codigo_mh' => 'TZ', 'nacionalidad' => 'Tanzana'],
            ['pais' => 'Tayikistán',                            'codigo_mh' => 'TJ', 'nacionalidad' => 'Tayika'],
            ['pais' => 'Territorio Británico Océano Indico',    'codigo_mh' => 'IO', 'nacionalidad' => ''],
            ['pais' => 'Territorio Australes Franceses',        'codigo_mh' => 'TF', 'nacionalidad' => ''],
            ['pais' => 'Timor Oriental',                        'codigo_mh' => 'TL', 'nacionalidad' => 'Timorense'],
            ['pais' => 'Togo',                                  'codigo_mh' => 'TG', 'nacionalidad' => 'Togolesa'],
            ['pais' => 'Tokelau',                               'codigo_mh' => 'TK', 'nacionalidad' => ''],
            ['pais' => 'Tonga',                                 'codigo_mh' => 'TO', 'nacionalidad' => 'Tongana'],
            ['pais' => 'Trinidad y Tobago',                     'codigo_mh' => 'TT', 'nacionalidad' => 'Trinitense y Tobaguense'],
            ['pais' => 'Túnez',                                 'codigo_mh' => 'TN', 'nacionalidad' => 'Tunecina'],
            ['pais' => 'Turkmenistán',                          'codigo_mh' => 'TM', 'nacionalidad' => 'Turcomana'],
            ['pais' => 'Turquía',                               'codigo_mh' => 'TR', 'nacionalidad' => 'Turca'],
            ['pais' => 'Tuvalu',                                'codigo_mh' => 'TV', 'nacionalidad' => 'Tuvaluana'],
            ['pais' => 'Ucrania',                               'codigo_mh' => 'UA', 'nacionalidad' => 'Ucraniana'],
            ['pais' => 'Uganda',                                'codigo_mh' => 'UG', 'nacionalidad' => 'Ugandesa'],
            ['pais' => 'Uruguay',                               'codigo_mh' => 'UY', 'nacionalidad' => 'Uruguaya'],
            ['pais' => 'Uzbekistán',                            'codigo_mh' => 'UZ', 'nacionalidad' => 'Uzbeka'],
            ['pais' => 'Vanuatu',                               'codigo_mh' => 'VU', 'nacionalidad' => 'Vanuatuense'],
            ['pais' => 'Venezuela',                             'codigo_mh' => 'VE', 'nacionalidad' => 'Venezolana'],
            ['pais' => 'Vietnam',                               'codigo_mh' => 'VN', 'nacionalidad' => ''],
            ['pais' => 'Islas Vírgenes Británicas',             'codigo_mh' => 'VG', 'nacionalidad' => ''],
            ['pais' => 'Wallis y Fortuna, Islas',               'codigo_mh' => 'WF', 'nacionalidad' => ''],
            ['pais' => 'Yemen',                                 'codigo_mh' => 'YE', 'nacionalidad' => 'Yemení'],
            ['pais' => 'Zambia',                                'codigo_mh' => 'ZM', 'nacionalidad' => 'Zambiana'],
            ['pais' => 'Zimbawe',                               'codigo_mh' => 'ZW', 'nacionalidad' => 'Zimbabuense'],


            /*['pais'=>'Dakota del Sur (USA)',    'codigo_mh'=>'9905','nacionalidad'=>'Dakotenses'],
            ['pais'=>'No Definido en Migración','codigo_mh'=>'9999','nacionalidad'=>''],
            ['pais'=>'Alto Volta',              'codigo_mh'=>'9315','nacionalidad'=>'Voltenses'],
            ['pais'=>'Birmania',                'codigo_mh'=>'9354','nacionalidad'=>'Birmana'],
            ['pais'=>'Bophuthatswana',          'codigo_mh'=>'9374','nacionalidad'=>'Burundesa'],
            ['pais'=>'Ceilán',                  'codigo_mh'=>'9387','nacionalidad'=>'Canadiense'],
            ['pais'=>'Checoslovaquia',                 'codigo_mh'=>'9420','nacionalidad'=>'Checa'],
            ['pais'=>'Dahomey',                        'codigo_mh'=>'9435','nacionalidad'=>''],
            ['pais'=>'Holanda',                        'codigo_mh'=>'9498','nacionalidad'=>'Holandes'],
            ['pais'=>'Nuevas Hebridas',                'codigo_mh'=>'9636','nacionalidad'=>''],
            ['pais'=>'Rodesia',                        'codigo_mh'=>'9669','nacionalidad'=>''],
            ['pais'=>'Suecilandia',                    'codigo_mh'=>'9708','nacionalidad'=>'Suazi'],
            ['pais'=>'Transkei',                       'codigo_mh'=>'9725','nacionalidad'=>''],
            ['pais'=>'URSS',                           'codigo_mh'=>'9732','nacionalidad'=>''],
            ['pais'=>'Vietnam del Norte',              'codigo_mh'=>'9744','nacionalidad'=>'Vietnamita'],
            ['pais'=>'Vietnam del Sur',                'codigo_mh'=>'9747','nacionalidad'=>'Vietnamita'],
            ['pais'=>'Yugoslavia',                     'codigo_mh'=>'9756','nacionalidad'=>''],
            ['pais'=>'Zaire',                          'codigo_mh'=>'9758','nacionalidad'=>''],
            ['pais'=>'Nueva Guinea',                   'codigo_mh'=>'9886','nacionalidad'=>'Guineana'],
            ['pais'=>'Ant Holandesas',                 'codigo_mh'=>'9898','nacionalidad'=>''],
            ['pais'=>'Alemania',                       'codigo_mh'=>'9311','nacionalidad'=>'Alemana'],
            ['pais'=>'Islas Azores',                   'codigo_mh'=>'9530','nacionalidad'=>''],
            ['pais'=>'Islas Qeshm',                    'codigo_mh'=>'9532','nacionalidad'=>''],
            ['pais'=>'Territorio Británico del Océano índico','codigo_mh'=>'9712','nacionalidad'=>''],
            ['pais'=>'Yibuti',                                'codigo_mh'=>'9751','nacionalidad'=>'Yibutiana'],
            ['pais'=>'Nevada (USA)',                          'codigo_mh'=>'9901','nacionalidad'=>''],
            ['pais'=>'Wyoming (USA)',                         'codigo_mh'=>'9902','nacionalidad'=>''],
            ['pais'=>'Campione D´Italia, Italina',            'codigo_mh'=>'9903','nacionalidad'=>''],
            ['pais'=>'Florida (USA)',                         'codigo_mh'=>'9904','nacionalidad'=>''],
            ['pais'=>'Inglaterra Y Gales',                    'codigo_mh'=>'9514','nacionalidad'=>''],
            ['pais'=>'Texas (USA)',                           'codigo_mh'=>'9906','nacionalidad'=>''],
            ['pais'=>'Isla de Man',                           'codigo_mh'=>'9521','nacionalidad'=>''],
            ['pais'=>'Territorios Australes Franceses',       'codigo_mh'=>'9713','nacionalidad'=>''],
            ['pais'=>'Islas Feroe',                           'codigo_mh'=>'9529','nacionalidad'=>''],
            ['pais'=>'Territorios Palestinos',                'codigo_mh'=>'9715','nacionalidad'=>''],
            ['pais'=>'Delaware (USA)',                        'codigo_mh'=>'9900','nacionalidad'=>''],
            ['pais'=>'Cabinda',                               'codigo_mh'=>'9376','nacionalidad'=>''],
            ['pais'=>'Washington (USA)',                      'codigo_mh'=>'9907','nacionalidad'=>''],*/
        ];

        foreach ($paises as $pais) {
            paises::firstOrCreate($pais);
        }
    }
}
